;;-----------------------------LICENSE NOTICE------------------------------------
;;  This file is part of CPCtelera: An Amstrad CPC Game Engine 
;;  Copyright (C) 2016 ronaldo / Fremos / Cheesetea / ByteRealms (@FranGallegoBR)
;;
;;  This program is free software: you can redistribute it and/or modify
;;  it under the terms of the GNU Lesser General Public License as published by
;;  the Free Software Foundation, either version 3 of the License, or
;;  (at your option) any later version.
;;
;;  This program is distributed in the hope that it will be useful,
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;  GNU Lesser General Public License for more details.
;;
;;  You should have received a copy of the GNU Lesser General Public License
;;  along with this program.  If not, see <http://www.gnu.org/licenses/>.
;;-------------------------------------------------------------------------------

;; Code modified to be used with ABASM by Javier "Dwayne Hicks" Garcia

org &2000
jp  main

;; Include CPCtelera opcode macros
read 'cpctelera/macros/cpct_undocumentedOpcodes.asm'

;;===============================================================================
;; DEFINED CONSTANTS
;;===============================================================================

pvideomem     equ &C000          ;; First byte of video memory
screen_H      equ 200            ;; Height of the screen in pixels
screen_W      equ 80             ;; Width of the screen in bytes
init_colour   equ &0001          ;; Background = &00, Foreground = &01
palete_size   equ 16             ;; Number of total palette colours
border_colour equ &1F10          ;; &10 (Border ID), &1F (Colour to set, Pen 0 from palette). Ready to be loaded into HL
initxy_sprite equ &C711          ;; (x, y) = (17, 200) = (&11, &C8) Initial Sprite coordinates in bytes
sprite_HxW    equ &852D          ;; Height (133, &85) and Width (45, &2D) of the sprite in bytes. To be loaded in BC   
sprite_end_y  equ 20             ;; y coordinate where sprite will stop its entering animation
clip_Height   equ screen_H - 133 ;; Minimum height at which to do clipping (200 - sprite_Height)
xy_str_dav    equ &0212          ;; y = 2 (&02), x = 18 (&12) (ready to be loaded into BC, B=y, C=x)  
itmusiccycles equ 6              ;; Number of interrupt cycles between music calls

;;;
;;; File generated by cpct_aks2c CPCtelera script
;;; Souce file of this conversion: assets/music.aks
;;; Generation time: miércoles, 23 de agosto de 2023, 12:38:04 CEST
;;;
org &2A41

;;; Music data start (    5567 bytes)
;;;
g_music:
db &41, &54, &31, &30, &01, &40, &42, &0f, &02, &05, &e8, &00, &69, &2a, &72, &2a
db &7c, &2a, &95, &2a, &a4, &2a, &ad, &2a, &c6, &2a, &d7, &2a, &e8, &2a, &f9, &2a
db &0a, &2b, &1b, &2b, &25, &2b, &2b, &2b, &00, &00, &00, &00, &00, &00, &0d, &6b
db &2a, &01, &00, &3c, &38, &30, &28, &1c, &0d, &6b, &2a, &01, &00, &3e, &09, &bc
db &80, &ff, &bc, &a0, &ff, &bc, &80, &00, &bc, &c0, &00, &bc, &d0, &00, &bc, &e0
db &00, &0d, &6b, &2a, &05, &fe, &25, &28, &0c, &05, &28, &25, &38, &18, &05, &38
db &0d, &97, &2a, &01, &00, &32, &05, &32, &05, &0d, &6b, &2a, &01, &00, &be, &22
db &6f, &fe, &be, &22, &ff, &fe, &be, &2f, &54, &ff, &ba, &2f, &78, &ff, &3c, &a0
db &d0, &ff, &0d, &6b, &2a, &02, &00, &7c, &0c, &3c, &b8, &ff, &ff, &ac, &fe, &ff
db &98, &ff, &ff, &0d, &6b, &2a, &02, &00, &7e, &25, &0c, &7c, &03, &78, &07, &2c
db &68, &03, &60, &07, &0d, &6b, &2a, &02, &00, &7e, &25, &0c, &7c, &04, &78, &07
db &2c, &68, &04, &60, &07, &0d, &6b, &2a, &02, &00, &7e, &25, &0c, &7c, &05, &78
db &09, &2c, &68, &05, &60, &09, &0d, &6b, &2a, &02, &00, &7e, &25, &0c, &7c, &04
db &78, &09, &2c, &68, &04, &60, &09, &0d, &6b, &2a, &02, &00, &3c, &7c, &03, &7c
db &07, &0d, &1d, &2b, &01, &00, &3c, &0d, &27, &2b, &02, &00, &3c, &7c, &04, &7c
db &07, &0d, &2d, &2b, &40, &00, &00, &00, &78, &2c, &00, &7a, &2c, &77, &2d, &fc
db &2c, &00, &50, &32, &7c, &2d, &26, &32, &00, &50, &32, &1e, &2d, &fc, &2c, &00
db &80, &3f, &1e, &2d, &26, &32, &00, &50, &32, &94, &2d, &fc, &2c, &00, &50, &32
db &0c, &2e, &fc, &2c, &00, &50, &32, &94, &2d, &fc, &2c, &00, &09, &2f, &b2, &2f
db &8c, &2f, &00, &86, &2e, &6c, &30, &e6, &30, &00, &86, &2e, &08, &31, &28, &30
db &00, &86, &2e, &2c, &39, &4a, &30, &00, &82, &31, &4e, &39, &04, &32, &00, &ed
db &32, &70, &33, &d3, &32, &00, &e3, &33, &a3, &35, &d3, &32, &00, &98, &38, &fa
db &37, &7c, &38, &00, &f7, &34, &3a, &36, &8a, &35, &02, &fd, &7a, &2c, &77, &34
db &2e, &36, &00, &50, &32, &77, &34, &2e, &36, &00, &47, &37, &0f, &37, &b9, &36
db &00, &02, &3a, &6e, &39, &a6, &39, &00, &e8, &3a, &0f, &37, &b9, &36, &02, &fd
db &9b, &3b, &b5, &3a, &4d, &3c, &02, &00, &ed, &32, &a7, &3c, &d3, &32, &00, &e3
db &33, &a3, &35, &d3, &32, &00, &98, &38, &fa, &37, &7c, &38, &00, &f7, &34, &3a
db &36, &8a, &35, &02, &fd, &47, &37, &0f, &37, &b9, &36, &00, &02, &3a, &6e, &39
db &a6, &39, &00, &e8, &3a, &0f, &37, &b9, &36, &00, &9b, &3b, &b5, &3a, &4d, &3c
db &0e, &ff, &02, &02, &47, &37, &0f, &37, &b9, &36, &00, &02, &3a, &6e, &39, &a6
db &39, &00, &e8, &3a, &0f, &37, &b9, &36, &00, &75, &3e, &b5, &3a, &22, &3f, &0c
db &ff, &ff, &50, &32, &94, &2d, &fc, &2c, &00, &50, &32, &0c, &2e, &fc, &2c, &00
db &50, &32, &94, &2d, &fc, &2c, &00, &09, &2f, &b2, &2f, &8c, &2f, &0e, &00, &00
db &00, &50, &32, &7c, &2d, &26, &32, &00, &50, &32, &1e, &2d, &fc, &2c, &00, &50
db &32, &1c, &3d, &fc, &2c, &00, &50, &32, &a0, &3d, &26, &32, &02, &f7, &ed, &32
db &2a, &3e, &24, &3e, &01, &cf, &2b, &15, &00, &aa, &e1, &00, &00, &01, &02, &92
db &40, &aa, &4b, &aa, &45, &92, &4b, &92, &45, &aa, &4b, &b0, &41, &92, &4b, &98
db &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41, &b8, &4b, &b4, &41, &a0, &4b, &9c
db &41, &b4, &4b, &b4, &45, &9c, &4b, &9c, &45, &b4, &4b, &ae, &41, &9c, &4b, &96
db &41, &ae, &4b, &a6, &41, &96, &4b, &8e, &41, &a6, &4b, &a2, &41, &8e, &4b, &8a
db &41, &a2, &4b, &a2, &45, &8a, &4b, &8a, &45, &a2, &4b, &b0, &41, &8a, &4b, &98
db &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41, &b8, &4b, &b4, &41, &a0, &4b, &9c
db &41, &b4, &4b, &b4, &45, &9c, &4b, &9c, &45, &b4, &4b, &be, &41, &9c, &4b, &a6
db &41, &be, &4b, &b4, &41, &a6, &4b, &9c, &41, &b4, &4b, &7e, &e0, &00, &00, &02
db &02, &62, &60, &03, &1a, &7e, &60, &02, &02, &5e, &60, &03, &1a, &7e, &60, &02
db &02, &5a, &60, &03, &1a, &7e, &60, &02, &02, &68, &60, &03, &00, &42, &80, &00
db &00, &02, &80, &60, &04, &02, &41, &02, &80, &60, &02, &02, &8a, &60, &05, &02
db &b0, &60, &04, &02, &71, &02, &71, &06, &59, &02, &59, &02, &7e, &60, &02, &02
db &8a, &60, &05, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &06
db &59, &02, &59, &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &98, &60, &04, &02
db &59, &02, &59, &06, &59, &02, &59, &02, &7e, &60, &02, &02, &8a, &60, &05, &06
db &7e, &60, &02, &02, &3f, &00, &42, &81, &00, &00, &00, &42, &80, &00, &00, &3e
db &2c, &7e, &60, &02, &02, &8a, &60, &05, &02, &4b, &02, &7e, &60, &02, &02, &8a
db &60, &05, &00, &aa, &e0, &00, &00, &06, &02, &80, &60, &04, &02, &aa, &60, &07
db &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &b0, &60, &04, &02, &71, &02, &71
db &02, &b4, &60, &06, &02, &98, &60, &04, &02, &a6, &60, &08, &02, &7e, &60, &02
db &02, &8a, &60, &05, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04
db &02, &ba, &60, &06, &02, &98, &60, &04, &02, &a2, &60, &08, &02, &7e, &60, &02
db &02, &8a, &60, &05, &02, &98, &60, &04, &02, &59, &02, &59, &02, &b4, &60, &06
db &02, &98, &60, &04, &02, &a6, &60, &08, &02, &7e, &60, &02, &02, &8a, &60, &05
db &02, &b0, &60, &06, &02, &7e, &60, &02, &02, &3f, &00, &aa, &e0, &00, &00, &06
db &02, &80, &60, &04, &02, &aa, &60, &07, &02, &7e, &60, &02, &02, &8a, &60, &05
db &02, &b0, &60, &04, &02, &71, &02, &71, &02, &b4, &60, &06, &02, &98, &60, &04
db &02, &a6, &60, &08, &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &98, &60, &04
db &02, &7e, &60, &02, &02, &98, &60, &04, &02, &aa, &60, &06, &02, &98, &60, &04
db &02, &a2, &60, &08, &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &98, &60, &04
db &02, &59, &02, &59, &02, &b0, &60, &06, &02, &98, &60, &04, &02, &a2, &60, &08
db &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &7e, &60, &02, &02, &b0, &60, &04
db &02, &7e, &60, &02, &00, &b6, &e1, &00, &00, &01, &98, &4b, &a8, &41, &b6, &4b
db &b6, &45, &a8, &4b, &a8, &45, &b6, &4b, &b6, &47, &a8, &4b, &a8, &47, &b6, &4b
db &ba, &41, &a8, &4b, &b4, &41, &ba, &4b, &ac, &41, &b4, &4b, &9c, &41, &ac, &4b
db &ac, &45, &9c, &4b, &9c, &45, &ac, &4b, &b0, &41, &9c, &4b, &98, &41, &b0, &4b
db &ac, &41, &98, &4b, &94, &41, &ac, &4b, &ac, &41, &94, &4b, &94, &41, &ac, &4b
db &a6, &41, &94, &4b, &ac, &41, &a6, &4b, &94, &41, &ac, &4b, &b4, &41, &94, &4b
db &9c, &41, &b4, &4b, &b6, &41, &9c, &4b, &9e, &41, &b6, &4b, &b4, &41, &9e, &4b
db &b0, &41, &b4, &4b, &98, &41, &b0, &4b, &b0, &47, &98, &4b, &98, &47, &b0, &4b
db &b0, &49, &98, &4b, &98, &49, &b0, &4b, &aa, &e1, &00, &00, &01, &9c, &4b, &92
db &41, &aa, &4b, &aa, &45, &92, &4b, &92, &45, &aa, &4b, &b0, &41, &92, &4b, &98
db &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41, &b8, &4b, &b4, &41, &a0, &4b, &9c
db &41, &b4, &4b, &b4, &45, &9c, &4b, &9c, &45, &b4, &4b, &ae, &41, &9c, &4b, &96
db &41, &ae, &4b, &a6, &41, &96, &4b, &8e, &41, &a6, &4b, &a2, &41, &8e, &4b, &8a
db &41, &a2, &4b, &a2, &45, &8a, &4b, &8a, &45, &a2, &4b, &b0, &41, &8a, &4b, &98
db &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41, &b8, &4b, &b4, &41, &a0, &4b, &9c
db &41, &b4, &4b, &ae, &45, &9c, &4b, &96, &45, &ae, &4b, &b0, &41, &96, &4b, &98
db &41, &b0, &4b, &b4, &41, &98, &4b, &9c, &41, &b4, &4b, &7e, &e0, &00, &00, &02
db &02, &62, &60, &03, &1a, &7e, &60, &02, &02, &5e, &60, &03, &1a, &7e, &60, &02
db &02, &5a, &60, &03, &1a, &7e, &60, &02, &02, &5e, &60, &03, &0a, &23, &06, &27
db &00, &aa, &e0, &00, &00, &06, &02, &80, &60, &04, &02, &aa, &60, &07, &02, &7e
db &60, &02, &02, &8a, &60, &05, &02, &b0, &60, &04, &02, &71, &02, &71, &02, &a6
db &60, &06, &02, &98, &60, &04, &02, &a6, &60, &08, &02, &7e, &60, &02, &02, &8a
db &60, &05, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &a2
db &60, &06, &02, &98, &60, &04, &02, &a2, &60, &08, &02, &7e, &60, &02, &02, &8a
db &60, &05, &02, &98, &60, &04, &02, &59, &02, &59, &02, &9c, &60, &06, &02, &98
db &60, &04, &02, &59, &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &4b, &02, &a6
db &60, &08, &02, &8a, &60, &05, &00, &7e, &e0, &00, &00, &02, &02, &60, &60, &03
db &1a, &7e, &60, &02, &02, &5e, &60, &03, &1a, &7e, &60, &02, &02, &5a, &60, &03
db &1a, &7e, &60, &02, &02, &68, &60, &03, &00, &7e, &e0, &00, &00, &02, &02, &60
db &60, &03, &1a, &7e, &60, &02, &02, &5e, &60, &03, &1a, &7e, &60, &02, &02, &64
db &60, &03, &1a, &7e, &60, &02, &02, &60, &60, &03, &00, &a8, &e0, &00, &00, &06
db &02, &80, &60, &04, &02, &a8, &60, &08, &02, &7e, &60, &02, &02, &8a, &60, &05
db &02, &b0, &60, &04, &02, &71, &02, &71, &02, &a6, &60, &06, &02, &98, &60, &04
db &02, &ac, &60, &08, &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &98, &60, &04
db &02, &7e, &60, &02, &02, &98, &60, &04, &02, &ac, &60, &06, &02, &98, &60, &04
db &02, &a6, &60, &07, &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &98, &60, &04
db &02, &59, &02, &59, &02, &b0, &60, &06, &02, &98, &60, &04, &02, &b0, &60, &07
db &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &ac, &60, &06, &02, &b0, &60, &07
db &02, &7e, &60, &02, &00, &7e, &e0, &00, &00, &02, &02, &60, &60, &03, &1a, &7e
db &60, &02, &02, &64, &60, &03, &1a, &7e, &60, &02, &02, &5e, &60, &03, &1a, &7e
db &60, &02, &02, &68, &60, &03, &00, &a8, &e0, &00, &00, &06, &02, &80, &60, &04
db &02, &a8, &60, &08, &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &b0, &60, &04
db &02, &71, &02, &71, &02, &a6, &60, &06, &02, &98, &60, &04, &02, &a6, &60, &07
db &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &98, &60, &04, &02, &7e, &60, &02
db &02, &98, &60, &04, &02, &ac, &60, &06, &02, &98, &60, &04, &02, &a2, &60, &09
db &02, &7e, &60, &02, &02, &8a, &60, &05, &02, &98, &60, &04, &02, &59, &02, &59
db &02, &b6, &60, &06, &02, &98, &60, &04, &02, &9e, &60, &0a, &02, &7e, &60, &02
db &02, &8a, &60, &05, &02, &a2, &60, &06, &02, &9e, &60, &0a, &02, &7e, &60, &02
db &00, &b6, &e1, &00, &00, &01, &02, &a8, &40, &b6, &4b, &b6, &45, &a8, &4b, &a8
db &45, &b6, &4b, &b6, &47, &a8, &4b, &a8, &47, &b6, &4b, &ba, &41, &a8, &4b, &b4
db &41, &ba, &4b, &ac, &41, &b4, &4b, &9c, &41, &ac, &4b, &ac, &45, &9c, &4b, &9c
db &45, &ac, &4b, &b0, &41, &9c, &4b, &98, &41, &b0, &4b, &ac, &41, &98, &4b, &94
db &41, &ac, &4b, &a4, &43, &94, &4b, &8c, &41, &a4, &4b, &9a, &41, &8c, &4b, &a4
db &41, &9a, &4b, &8c, &41, &a4, &4b, &b2, &41, &8c, &4b, &9a, &41, &b2, &4b, &bc
db &41, &9a, &4b, &a4, &41, &bc, &4b, &bc, &43, &a4, &4b, &a4, &43, &bc, &4b, &bc
db &45, &a4, &4b, &a4, &45, &bc, &4b, &bc, &47, &a4, &4b, &a4, &47, &bc, &4b, &bc
db &49, &a4, &4b, &7e, &e0, &00, &00, &02, &02, &60, &60, &03, &1a, &7e, &60, &02
db &02, &5e, &60, &03, &1a, &7e, &60, &02, &02, &74, &60, &03, &1a, &7e, &60, &02
db &02, &5c, &60, &03, &00, &7e, &e0, &00, &00, &02, &02, &62, &60, &03, &1a, &7e
db &60, &02, &02, &5e, &60, &03, &1a, &7e, &60, &02, &02, &5a, &60, &03, &1a, &7e
db &60, &02, &02, &50, &60, &03, &0a, &7e, &60, &02, &02, &54, &60, &03, &00, &aa
db &e1, &00, &00, &01, &9c, &4b, &92, &41, &aa, &4b, &aa, &45, &92, &4b, &92, &45
db &aa, &4b, &b0, &41, &92, &4b, &98, &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41
db &b8, &4b, &b4, &41, &a0, &4b, &9c, &41, &b4, &4b, &b4, &45, &9c, &4b, &9c, &45
db &b4, &4b, &ae, &41, &9c, &4b, &96, &41, &ae, &4b, &a6, &41, &96, &4b, &8e, &41
db &a6, &4b, &a2, &41, &8e, &4b, &8a, &41, &a2, &4b, &a2, &45, &8a, &4b, &8a, &45
db &a2, &4b, &b0, &41, &8a, &4b, &98, &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41
db &b8, &4b, &b4, &41, &a0, &4b, &9c, &41, &b4, &4b, &b4, &45, &9c, &4b, &9c, &45
db &b4, &4b, &be, &41, &9c, &4b, &a6, &41, &be, &4b, &b4, &41, &a6, &4b, &9c, &41
db &b4, &4b, &74, &e0, &00, &00, &03, &3e, &30, &42, &80, &02, &00, &42, &00, &42
db &00, &42, &00, &42, &00, &42, &00, &42, &00, &42, &60, &00, &a4, &e1, &00, &00
db &01, &bc, &4b, &bc, &41, &a4, &4b, &a4, &43, &bc, &4b, &bc, &43, &a4, &4b, &a4
db &45, &bc, &4d, &bc, &45, &a4, &4d, &a4, &47, &bc, &4f, &bc, &47, &a4, &4f, &a4
db &49, &bc, &51, &bc, &49, &a4, &51, &a4, &4b, &bc, &53, &bc, &4b, &a4, &53, &a4
db &4d, &bc, &55, &bc, &4d, &a4, &55, &a4, &4f, &bc, &57, &bc, &4f, &a4, &57, &a4
db &51, &bc, &59, &bc, &51, &a4, &59, &a4, &53, &bc, &5b, &bc, &53, &a4, &5b, &a4
db &55, &bc, &5d, &bc, &55, &a4, &5d, &a4, &57, &bc, &5d, &bc, &57, &a4, &5d, &a4
db &59, &bc, &5d, &bc, &59, &a4, &5d, &a4, &5b, &bc, &5d, &bc, &5b, &a4, &5d, &a4
db &40, &bc, &40, &bc, &40, &a4, &40, &a4, &40, &bc, &40, &bc, &40, &a4, &40, &a4
db &fd, &00, &00, &0b, &02, &42, &1b, &02, &42, &19, &02, &42, &17, &02, &42, &15
db &02, &42, &13, &02, &42, &11, &02, &42, &0f, &02, &42, &0d, &02, &42, &09, &02
db &42, &07, &02, &42, &09, &02, &42, &0b, &02, &42, &09, &02, &42, &07, &02, &42
db &09, &02, &42, &0b, &42, &0d, &42, &09, &42, &0d, &42, &07, &42, &0d, &42, &09
db &42, &0f, &42, &0b, &42, &0f, &42, &09, &42, &0f, &42, &07, &42, &11, &42, &09
db &42, &11, &42, &0b, &42, &13, &42, &09, &42, &13, &42, &07, &42, &13, &42, &09
db &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &42, &07, &42, &13, &42, &09
db &42, &13, &a4, &eb, &00, &00, &0b, &42, &13, &42, &09, &42, &13, &8a, &6f, &05
db &a4, &60, &0b, &42, &09, &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a
db &6d, &05, &a4, &60, &0b, &42, &09, &42, &13, &42, &0b, &42, &13, &42, &09, &42
db &13, &8a, &6b, &05, &a4, &60, &0b, &42, &09, &42, &13, &42, &0b, &42, &13, &42
db &09, &42, &13, &8a, &69, &05, &a4, &60, &0b, &42, &00, &42, &13, &42, &0b, &42
db &13, &42, &09, &42, &13, &8a, &67, &05, &a4, &60, &0b, &42, &09, &42, &13, &42
db &0b, &42, &13, &42, &09, &42, &13, &8a, &65, &05, &a4, &60, &0b, &42, &09, &42
db &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &63, &05, &a4, &60, &0b, &42
db &09, &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &60
db &0b, &42, &09, &8a, &61, &05, &7e, &e1, &00, &00, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02
db &7e, &60, &02, &02, &3f, &00, &a4, &eb, &00, &00, &0b, &42, &13, &42, &09, &42
db &13, &8a, &61, &05, &a4, &6f, &0b, &42, &09, &42, &13, &42, &0b, &42, &13, &42
db &09, &42, &13, &8a, &61, &05, &a4, &6d, &0b, &42, &09, &42, &13, &42, &0b, &42
db &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &6b, &0b, &42, &09, &42, &13, &42
db &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &69, &0b, &42, &00, &42
db &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &67, &0b, &42
db &09, &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &65
db &0b, &42, &09, &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05
db &a4, &63, &0b, &42, &09, &42, &13, &42, &8b, &0a, &00, &42, &13, &42, &09, &42
db &13, &42, &07, &42, &13, &42, &09, &42, &13, &74, &e0, &00, &00, &03, &3e, &30
db &42, &80, &0a, &00, &42, &00, &42, &00, &42, &00, &42, &00, &42, &00, &42, &00
db &42, &00, &a4, &e1, &00, &00, &01, &bc, &4b, &bc, &41, &a4, &4b, &a4, &43, &bc
db &4b, &bc, &43, &a4, &4b, &a4, &45, &bc, &4d, &bc, &45, &a4, &4d, &a4, &47, &bc
db &4f, &bc, &47, &a4, &4f, &a4, &49, &bc, &51, &bc, &49, &a4, &51, &a4, &4b, &bc
db &53, &bc, &4b, &a4, &53, &a4, &4d, &bc, &55, &bc, &4d, &a4, &55, &a4, &4f, &bc
db &57, &bc, &4f, &a4, &57, &a4, &51, &bc, &59, &bc, &51, &a4, &59, &a4, &53, &bc
db &5b, &bc, &53, &a4, &5b, &a4, &55, &bc, &5d, &bc, &55, &a4, &5d, &a4, &57, &bc
db &5d, &bc, &57, &a4, &5d, &a4, &59, &bc, &5d, &bc, &59, &a4, &5d, &a4, &5b, &bc
db &5d, &bc, &5b, &a4, &5d, &7e, &61, &02, &bc, &7d, &01, &7e, &61, &02, &a4, &7d
db &01, &7e, &61, &02, &bc, &7d, &01, &7e, &61, &02, &a4, &7d, &01, &74, &e0, &00
db &00, &03, &1e, &31, &1e, &2d, &1e, &3b, &00, &7e, &e1, &00, &00, &02, &02, &b0
db &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0
db &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0
db &60, &04, &02, &7e, &60, &02, &06, &7e, &40, &02, &b0, &60, &04, &02, &7e, &60
db &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60
db &02, &02, &74, &65, &0c, &02, &7e, &61, &02, &02, &b0, &60, &04, &02, &7e, &60
db &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &8c, &60, &03, &b0, &60, &04, &8c
db &60, &03, &7e, &60, &02, &02, &b0, &60, &04, &02, &7e, &60, &02, &3f, &b0, &60
db &04, &7e, &60, &02, &3f, &02, &3f, &00, &7e, &e0, &00, &00, &02, &5c, &60, &03
db &0c, &7e, &60, &02, &5c, &60, &03, &5c, &60, &0c, &05, &74, &60, &03, &06, &7e
db &60, &02, &58, &60, &03, &0c, &7e, &60, &02, &58, &60, &03, &70, &60, &0c, &19
db &70, &60, &03, &06, &7e, &60, &02, &54, &60, &03, &0c, &7e, &60, &02, &54, &60
db &03, &6c, &60, &0c, &15, &54, &60, &03, &06, &7e, &60, &02, &62, &60, &03, &0c
db &7e, &60, &02, &62, &60, &03, &62, &60, &0c, &0b, &7a, &60, &03, &00, &a4, &e1
db &00, &00, &06, &04, &65, &04, &61, &02, &65, &02, &4d, &0a, &6f, &04, &6f, &04
db &6b, &02, &6f, &02, &57, &02, &69, &02, &61, &02, &75, &04, &75, &04, &73, &02
db &75, &02, &5d, &02, &73, &02, &5b, &02, &6f, &04, &6f, &04, &6b, &02, &6f, &02
db &6b, &02, &6f, &02, &73, &00, &aa, &e1, &00, &00, &01, &9c, &4b, &68, &61, &04
db &aa, &6b, &01, &8a, &61, &05, &92, &6b, &01, &68, &61, &04, &aa, &6b, &01, &b0
db &41, &92, &4b, &68, &61, &04, &b0, &6b, &01, &8a, &61, &05, &98, &6b, &01, &68
db &61, &04, &b8, &6b, &01, &b4, &41, &a0, &4b, &68, &61, &04, &b4, &6b, &01, &8a
db &61, &05, &9c, &6b, &01, &68, &61, &04, &b4, &6b, &01, &ae, &41, &9c, &4b, &68
db &61, &04, &ae, &6b, &01, &8a, &61, &05, &96, &6b, &01, &68, &61, &04, &a6, &6b
db &01, &a2, &41, &8e, &4b, &68, &61, &04, &a2, &6b, &01, &8a, &61, &05, &8a, &6b
db &01, &68, &61, &04, &a2, &6b, &01, &b0, &41, &8a, &4b, &68, &61, &04, &b0, &6b
db &01, &8a, &61, &05, &98, &6b, &01, &68, &61, &04, &b8, &6b, &01, &b4, &41, &a0
db &4b, &68, &61, &04, &b4, &6b, &01, &8a, &61, &05, &9c, &6b, &01, &68, &61, &04
db &b4, &6b, &01, &be, &41, &9c, &4b, &68, &61, &04, &be, &6b, &01, &8a, &61, &05
db &a6, &6b, &01, &68, &61, &04, &b4, &6b, &01, &7e, &e1, &00, &00, &02, &02, &98
db &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98
db &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98
db &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98
db &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98
db &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98
db &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &98
db &60, &04, &02, &7e, &60, &02, &02, &98, &60, &04, &02, &7e, &60, &02, &02, &5c
db &60, &0c, &02, &7e, &60, &02, &02, &5c, &60, &0c, &00, &74, &e0, &00, &00, &03
db &3e, &32, &42, &60, &00, &74, &60, &03, &42, &60, &00, &74, &60, &03, &42, &60
db &00, &74, &60, &03, &42, &60, &00, &a4, &eb, &00, &00, &0b, &42, &13, &42, &09
db &42, &13, &8a, &61, &05, &a4, &6f, &0b, &42, &09, &42, &13, &42, &0b, &42, &13
db &42, &09, &42, &13, &8a, &61, &05, &a4, &6d, &0b, &42, &09, &42, &13, &42, &0b
db &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &6b, &0b, &42, &09, &42, &13
db &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &69, &0b, &42, &00
db &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4, &67, &0b
db &42, &09, &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61, &05, &a4
db &65, &0b, &42, &09, &42, &13, &42, &0b, &42, &13, &42, &09, &42, &13, &8a, &61
db &05, &a4, &63, &0b, &42, &09, &42, &13, &42, &0b, &42, &19, &42, &09, &42, &19
db &8a, &61, &05, &a4, &79, &0b, &42, &09, &8a, &63, &05, &b6, &e0, &00, &00, &06
db &0e, &77, &02, &7b, &06, &75, &06, &71, &02, &6d, &16, &6d, &0a, &67, &02, &6d
db &02, &7b, &06, &77, &06, &75, &02, &71, &0e, &71, &02, &75, &00, &b6, &e0, &00
db &00, &06, &0e, &77, &02, &7b, &06, &75, &06, &71, &02, &6d, &12, &67, &02, &6d
db &0a, &65, &02, &6d, &02, &73, &06, &71, &06, &6d, &02, &65, &00, &a4, &e1, &00
db &00, &06, &04, &65, &04, &61, &02, &65, &02, &4d, &0a, &6f, &04, &6f, &04, &6b
db &02, &6f, &02, &57, &02, &69, &02, &61, &02, &65, &04, &65, &04, &61, &02, &65
db &02, &4d, &02, &5d, &02, &45, &02, &6b, &04, &6b, &04, &69, &02, &6b, &02, &5b
db &02, &6f, &02, &69, &00, &7e, &e0, &00, &00, &02, &5c, &60, &03, &0c, &7e, &60
db &02, &5c, &60, &03, &74, &60, &0c, &1d, &74, &60, &03, &06, &7e, &60, &02, &58
db &60, &03, &0c, &7e, &60, &02, &58, &60, &03, &70, &60, &0c, &19, &58, &60, &03
db &06, &7e, &60, &02, &54, &60, &03, &0c, &7e, &60, &02, &54, &60, &03, &6c, &60
db &0c, &15, &6c, &60, &03, &06, &7e, &60, &02, &62, &60, &03, &0c, &7e, &60, &02
db &66, &60, &03, &66, &60, &0c, &0f, &66, &60, &03, &02, &7e, &60, &02, &66, &60
db &03, &aa, &e1, &00, &00, &01, &9c, &4b, &68, &61, &04, &aa, &6b, &01, &8a, &61
db &05, &92, &6b, &01, &68, &61, &04, &aa, &6b, &01, &b0, &41, &92, &4b, &68, &61
db &04, &b0, &6b, &01, &8a, &61, &05, &98, &6b, &01, &68, &61, &04, &b8, &6b, &01
db &b4, &41, &a0, &4b, &68, &61, &04, &b4, &6b, &01, &8a, &61, &05, &9c, &6b, &01
db &68, &61, &04, &b4, &6b, &01, &ae, &41, &9c, &4b, &68, &61, &04, &ae, &6b, &01
db &8a, &61, &05, &96, &6b, &01, &68, &61, &04, &a6, &6b, &01, &a2, &41, &8e, &4b
db &68, &61, &04, &a2, &6b, &01, &8a, &61, &05, &8a, &6b, &01, &68, &61, &04, &a2
db &6b, &01, &b0, &41, &8a, &4b, &68, &61, &04, &b0, &6b, &01, &8a, &61, &05, &98
db &6b, &01, &68, &61, &04, &b8, &6b, &01, &b4, &41, &a0, &4b, &68, &61, &04, &b4
db &6b, &01, &8a, &61, &05, &9c, &6b, &01, &68, &61, &04, &b4, &6b, &01, &be, &41
db &9c, &4b, &68, &61, &04, &be, &6b, &01, &8a, &61, &05, &a6, &6b, &01, &68, &61
db &04, &8a, &60, &05, &a4, &e1, &00, &00, &06, &04, &65, &04, &61, &02, &65, &02
db &4d, &0a, &61, &04, &61, &04, &5d, &02, &61, &02, &49, &02, &5b, &02, &53, &02
db &5d, &04, &5d, &04, &5b, &02, &5d, &02, &45, &0a, &57, &04, &57, &04, &53, &02
db &57, &02, &61, &02, &65, &6f, &00, &aa, &e1, &00, &00, &01, &9c, &4b, &aa, &61
db &07, &aa, &6b, &01, &8a, &61, &05, &92, &6b, &01, &aa, &61, &07, &aa, &6b, &01
db &b0, &41, &92, &4b, &aa, &61, &07, &b0, &6b, &01, &8a, &61, &05, &98, &6b, &01
db &aa, &61, &07, &b8, &6b, &01, &b4, &41, &a0, &4b, &a6, &61, &08, &b4, &6b, &01
db &8a, &61, &05, &9c, &6b, &01, &a6, &61, &08, &b4, &6b, &01, &ae, &41, &9c, &4b
db &a6, &61, &08, &ae, &6b, &01, &8a, &61, &05, &96, &6b, &01, &a6, &61, &08, &a6
db &6b, &01, &a2, &41, &8e, &4b, &a2, &61, &08, &a2, &6b, &01, &8a, &61, &05, &8a
db &6b, &01, &a2, &61, &08, &a2, &6b, &01, &b0, &41, &8a, &4b, &a2, &61, &08, &b0
db &6b, &01, &8a, &61, &05, &98, &6b, &01, &a2, &61, &08, &b8, &6b, &01, &b4, &41
db &a0, &4b, &a6, &61, &08, &b4, &6b, &01, &8a, &61, &05, &9c, &6b, &01, &a6, &61
db &08, &b4, &6b, &01, &be, &41, &9c, &4b, &a6, &61, &08, &be, &6b, &01, &8a, &61
db &05, &a6, &6b, &01, &a6, &61, &08, &b4, &6b, &01, &aa, &e1, &00, &00, &01, &9c
db &4b, &aa, &61, &07, &aa, &6b, &01, &8a, &61, &05, &92, &6b, &01, &aa, &61, &07
db &aa, &6b, &01, &b0, &41, &92, &4b, &aa, &61, &07, &b0, &6b, &01, &8a, &61, &05
db &98, &6b, &01, &aa, &61, &07, &b8, &6b, &01, &b4, &41, &a0, &4b, &a6, &61, &08
db &b4, &6b, &01, &8a, &61, &05, &9c, &6b, &01, &a6, &61, &08, &b4, &6b, &01, &ae
db &41, &9c, &4b, &a6, &61, &08, &ae, &6b, &01, &8a, &61, &05, &96, &6b, &01, &a6
db &61, &08, &a6, &6b, &01, &a2, &41, &8e, &4b, &a2, &61, &08, &a2, &6b, &01, &8a
db &61, &05, &8a, &6b, &01, &a2, &61, &08, &a2, &6b, &01, &b0, &41, &8a, &4b, &a2
db &61, &08, &b0, &6b, &01, &8a, &61, &05, &98, &6b, &01, &a2, &61, &08, &b8, &6b
db &01, &b4, &41, &a0, &4b, &a2, &61, &08, &b4, &6b, &01, &8a, &61, &05, &9c, &6b
db &01, &a2, &61, &08, &ae, &6b, &01, &b0, &41, &96, &4b, &a2, &61, &08, &b0, &6b
db &01, &8a, &61, &05, &8a, &40, &a2, &60, &08, &8a, &60, &05, &7e, &e0, &00, &00
db &02, &5c, &60, &03, &0c, &7e, &60, &02, &5c, &60, &03, &74, &60, &0c, &1d, &74
db &60, &03, &06, &7e, &60, &02, &58, &60, &03, &0c, &7e, &60, &02, &58, &60, &03
db &70, &60, &0c, &19, &58, &60, &03, &06, &7e, &60, &02, &54, &60, &03, &0c, &7e
db &60, &02, &54, &60, &03, &6c, &60, &0c, &15, &6c, &60, &03, &06, &7e, &60, &02
db &62, &60, &03, &0c, &7e, &60, &02, &66, &60, &03, &66, &60, &0c, &0f, &7e, &60
db &02, &02, &3f, &66, &60, &03, &7e, &e1, &00, &00, &02, &a4, &7d, &0b, &42, &1b
db &02, &42, &19, &02, &42, &17, &02, &42, &15, &02, &42, &13, &02, &42, &11, &02
db &42, &0f, &02, &42, &0d, &02, &42, &09, &02, &42, &07, &02, &42, &09, &02, &42
db &0b, &02, &42, &09, &02, &42, &07, &02, &42, &09, &02, &42, &0b, &42, &0d, &42
db &09, &42, &0d, &42, &07, &42, &0d, &42, &09, &42, &0f, &42, &0b, &42, &0f, &42
db &09, &42, &0f, &42, &07, &42, &11, &42, &09, &42, &11, &42, &0b, &42, &13, &42
db &09, &42, &13, &42, &07, &42, &13, &42, &09, &42, &13, &42, &0b, &42, &13, &42
db &09, &42, &13, &42, &07, &42, &13, &42, &09, &42, &13, &aa, &f1, &00, &00, &0b
db &42, &0f, &42, &0d, &42, &0b, &42, &09, &42, &07, &42, &05, &42, &03, &42, &01
db &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42, &01, &42, &13, &a6, &60
db &0d, &42, &11, &42, &0f, &42, &0d, &42, &09, &42, &07, &42, &05, &42, &03, &42
db &01, &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42, &01, &42, &13, &a2
db &40, &42, &11, &42, &0f, &42, &0d, &42, &09, &42, &07, &42, &05, &42, &03, &42
db &01, &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42, &01, &42, &13, &a6
db &40, &42, &11, &42, &0f, &42, &0d, &42, &09, &42, &07, &42, &05, &42, &03, &42
db &01, &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42, &01, &42, &13, &aa
db &f1, &00, &00, &0b, &42, &0f, &42, &0d, &42, &0b, &42, &09, &42, &07, &42, &05
db &42, &03, &42, &01, &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42, &01
db &42, &13, &a6, &60, &0d, &42, &11, &42, &0f, &42, &0d, &42, &09, &42, &07, &42
db &05, &42, &03, &42, &01, &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42
db &01, &42, &13, &a2, &40, &42, &11, &42, &0f, &42, &0d, &42, &09, &42, &07, &42
db &05, &42, &03, &42, &01, &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42
db &01, &42, &13, &a2, &40, &42, &11, &42, &0f, &42, &0d, &42, &09, &42, &07, &42
db &05, &42, &03, &42, &01, &42, &0d, &42, &01, &42, &0f, &42, &01, &42, &11, &42
db &01, &42, &13, &62, &e0, &00, &00, &03, &00, &92, &f3, &00, &00, &0b, &02, &42
db &11, &02, &42, &0f, &02, &42, &0d, &02, &42, &0b, &02, &42, &09, &02, &42, &07
db &02, &42, &05, &02, &42, &03, &02, &42, &01, &02, &42, &03, &02, &42, &05, &02
db &42, &07, &02, &42, &09, &02, &42, &0b, &02, &42, &0d, &02, &42, &0f, &02, &42
db &11, &02, &42, &13, &02, &42, &15, &02, &42, &17, &02, &42, &19, &02, &42, &1b
db &02, &42, &1d, &00, &aa, &e1, &00, &00, &01, &9c, &4b, &aa, &61, &07, &aa, &6b
db &01, &8a, &61, &05, &92, &6b, &01, &aa, &61, &07, &aa, &6b, &01, &b0, &41, &92
db &4b, &aa, &61, &07, &b0, &6b, &01, &8a, &61, &05, &98, &6b, &01, &aa, &61, &07
db &b8, &6b, &01, &b4, &41, &a0, &4b, &a6, &61, &08, &b4, &6b, &01, &8a, &61, &05
db &9c, &6b, &01, &a6, &61, &08, &b4, &6b, &01, &ae, &41, &9c, &4b, &a6, &61, &08
db &ae, &6b, &01, &8a, &61, &05, &96, &6b, &01, &a6, &61, &08, &a6, &6b, &01, &a2
db &41, &8e, &4b, &a2, &61, &08, &a2, &6b, &01, &8a, &61, &05, &8a, &6b, &01, &a2
db &61, &08, &a2, &6b, &01, &b0, &41, &8a, &4b, &a2, &61, &08, &b0, &6b, &01, &8a
db &61, &05, &98, &6b, &01, &a2, &61, &08, &b8, &6b, &01, &b4, &41, &a0, &4b, &a2
db &61, &08, &b4, &6b, &01, &8a, &61, &05, &9c, &6b, &01, &a2, &61, &08, &ae, &6b
db &01, &b0, &41, &96, &4b, &98, &41, &b0, &4b, &b4, &41, &98, &4b, &9c, &41, &b4
db &4b, &7e, &e0, &00, &00, &02, &5c, &60, &03, &0c, &7e, &60, &02, &5c, &60, &03
db &74, &60, &0c, &1d, &74, &60, &03, &06, &7e, &60, &02, &58, &60, &03, &0c, &7e
db &60, &02, &58, &60, &03, &70, &60, &0c, &19, &58, &60, &03, &06, &7e, &60, &02
db &54, &60, &03, &0c, &7e, &60, &02, &54, &60, &03, &6c, &60, &0c, &15, &6c, &60
db &03, &06, &7e, &60, &02, &62, &60, &03, &0c, &7e, &60, &02, &66, &60, &03, &66
db &60, &0c, &42, &60, &00, &7e, &60, &02, &66, &60, &03, &02, &42, &60, &00, &aa
db &e1, &00, &00, &01, &9c, &4b, &92, &41, &aa, &4b, &aa, &45, &92, &4b, &92, &45
db &aa, &4b, &b0, &41, &92, &4b, &98, &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41
db &b8, &4b, &b4, &41, &a0, &4b, &9c, &41, &b4, &4b, &b4, &45, &9c, &4b, &9c, &45
db &b4, &4b, &ae, &41, &9c, &4b, &96, &41, &ae, &4b, &a6, &41, &96, &4b, &8e, &41
db &a6, &4b, &a2, &41, &8e, &4b, &8a, &41, &a2, &4b, &a2, &45, &8a, &4b, &8a, &45
db &a2, &4b, &b0, &41, &8a, &4b, &98, &41, &b0, &4b, &b8, &41, &98, &4b, &a0, &41
db &b8, &4b, &b4, &41, &a0, &4b, &9c, &41, &b4, &4b, &b4, &45, &9c, &4b, &9c, &45
db &b4, &4b, &a6, &71, &0d, &42, &0f, &42, &0d, &42, &0b, &42, &60, &00, &00

;; We will rely on the lower ROM to print the characters. The above ORG and
;; music data leaves us here in the address 0x4000, just the first adress out of
;; the lower ROM memory range.

;; Interrupt status counter
iscount:   db itmusiccycles

;; Ascii zero-terminated strings
str_happy: db "Happy",0
str_bday:  db "Birthday",0
str_dav:   db "@octopusjig",0

;; Scrolling data structures for both scrolling strings (Happy / BDay)
tscroll_happy: 
   dw   str_happy       ;; String pointer (2 bytes)
   db   1, 20*8         ;; x, y starting coordinates (y=20th character line)
   db  -1               ;; x velocity
   db   screen_W-5*4-1  ;; maxX coordinate: line-size (80) - 5 chars * 4 bytes/char - 1 (to set boundary 1 byte before)

tscroll_bday: 
   dw   str_bday        ;; String pointer (2 bytes)
   db   47, 23*8        ;; x, y starting coordinates (y=23th character line)
   db    1              ;; x velocity 
   db   screen_W-8*4-1  ;; maxX coordinate: line-size (80) - 8 chars * 4 bytes/char - 1 (to set boundary 1 byte before)

;; CPCtelera functions we want to use
read 'cpctelera/audio/arkostracker.asm'

read 'cpctelera/video/cpct_setVideoMode.asm'
read 'cpctelera/video/cpct_setPalette.asm'
read 'cpctelera/video/cpct_setPALColour.asm'
read 'cpctelera/video/cpct_getScreenPtr.asm'
read 'cpctelera/sprites/cpct_drawSprite.asm'
read 'cpctelera/video/cpct_waitVSYNC.asm'
read 'cpctelera/strings/cpct_drawStringM0.asm'
read 'cpctelera/strings/cpct_setDrawCharM0.asm'
read 'cpctelera/firmware/cpct_removeInterruptHandler.asm'
read 'cpctelera/firmware/cpct_setInterruptHandler.asm'

interrupt_handler:
   ;; Update interrupt counter variable (iscount)
   ld   hl, iscount           ;; HL points to interrupt counter variable (iscount)
   dec (hl)                   ;; --iscount
   ret  nz                    ;; Do not play music if iscount != 0 (so, return)

   ;; Play music
   ld    (hl), itmusiccycles  ;; Restore interrupt counter variable intial value
   call  cpct_akp_musicPlay   ;; Play the music

   ret                        ;; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; FUNC: init
;;    Sets CPC to its initial status
;; DESTROYS:
;;    AF, BC, DE, HL
;;
init:
   ;; Disable Firmware
   call  cpct_disableFirmware   ;; Disable firmware

   ;; Set Mode 0
   ld    c, 0                   ;; C = 0 (New video mode)
   call  cpct_setVideoMode      ;; Set Mode 0
   
   ;; Set Palette
   ld    hl, g_palette          ;; HL = pointer to the start of the palette array
   ld    de, palete_size        ;; DE = Size of the palette array (num of colours)
   call  cpct_setPalette        ;; Set the new palette

   ;; Change border colour
   ld    hl, border_colour      ;; L=Border colour value, H=Palette Colour to be set (Border=16)
   call  cpct_setPALColour      ;; Set the border (colour 16)

   ;; Initialize music
   ld    de, g_music            ;; DE points to the start of the song to be initialized
   call  cpct_akp_musicInit     ;; Initalize arkos tracker player with the song pointed by DE

   ;; 
   ld    hl, interrupt_handler    ;; HL points to the interrupt handler routine
   call  cpct_setInterruptHandler ;; Set the new interrupt handler routine

   ret                            ;; return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; FUNC: drawSpriteClipped
;;    Draw sprite with down clippling
;; INPUT:
;;    B: y pixel coordinate where to draw the sprite
;;    C: x pixel coordinate where to draw the sprite
;; DESTROYS:
;;    AF, BC, DE, HL
;;
drawSpriteClipped:
   ;; Calculate the memory location where the sprite will be drawn
   push  bc                     ;; save x,y coordinates passed as parameters
   ld    de, pvideomem          ;; DE points to the start of video memory
   call  cpct_getScreenPtr      ;; Return pointer to byte located at (x,y) (C, B) in HL
   ex    de, hl                 ;; DE = pointer to video memory location to draw the sprite
   pop   af                     ;; A = y coordinate

   ;; Check if clipping is needed
   ld    bc, sprite_HxW         ;; WidthxHeight of the sprite in bytes
   cp    clip_Height            ;; Compare A with clipping height: y coordinate where clipping starts
   jr     c, no_clip            ;; If Carry, (A < 160), no need to do clipping

   ;; Perform clippling (A = vertical size of the sprite to be drawn)
   sub   screen_H               ;; A2 =  A - screen_Height
   neg                          ;; A3 = -A2 = screen_Height - A
   ld     b, a                  ;; B = Reduced sprite height (clipped) to be drawn

no_clip:
   ;; Draw the sprite 
   ;; - DE already points to video mem, and BC contains WidthxHeight)
   ld    hl, g_octopusjig      ;; HL points to the sprite
   call  cpct_drawSprite       ;; Draw the sprite on the screen

   ret                         ;; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; FUNC: moveSprite
;;    Moves the sprite from down the screen to its final location in a
;; simple, linear animation.
;; DESTROYS:
;;    AF, BC, DE, HL
;;
moveSprite:
   ;; Draw Sprite After VSYNC
   call  cpct_waitVSYNC   ;; Wait for VSYNC

   y_coord equ $+2            ;; Location in memory of the value for the Y coordinate
   ld    bc, initxy_sprite    ;; BC takes XY coordinates (value loaded is modified dynamically)
   call  drawSpriteClipped    ;; Draw the sprite

   ;; Move Sprite Up
   ld    hl, y_coord          ;; HL points to y_coord in memory
   ld     a, (hl)             ;; A = y (Vertical coordinate)
   cp    sprite_end_y         ;; Check against y coordinate where sprite has to end its animation (end_y)
   ret   z                    ;; If y==end_y, end of the animation (no more coordinate update)

   dec   (hl)                 ;; Move sprite 1 pixel UP (y--)

   jr    moveSprite           ;; Loop again


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; FUNC: redrawString
;;    Draws a string with a new colour value each time, on a given location
;; INPUT:
;;    IY: Pointer to the string
;;    B: y pixel coordinate where to draw the string
;;    C: x pixel coordinate where to draw the string
;; DESTROYS:
;;    AF, BC, DE, HL
;;
redrawString:
   ;; Calculate screen location where to draw the string
   ;; BC Already have screen coordinates for the string to be drawn
   ld    de, pvideomem          ;; DE points to the start of video memory
   call  cpct_getScreenPtr      ;; Return pointer to byte located at (x,y) (C, B) in HL
   push  hl                     ;; Returns HL = Pointer to video memory (Required by drawStringM0)
                                ;; We save it for later use
   ;; Set colours to be used by DrawChar/DrawStringM0 functions
   fg_colour equ $+1            ;; fg_colour = location in memory of the Foreground colour value
   ld    hl, init_colour        ;; HL = fg/bg colours (value modified dynamically)
   call  cpct_setDrawCharM0     ;; Set colours before using DrawStringM0

   ;; Draw the string (IY points to the string)
   pop   hl                     ;; HL Points to video memory location where the string will be drawn
   call  cpct_drawStringM0      ;; Draw the string

   ;; Increment colour for next call
   ld     a, (fg_colour)         ;; A = Foreground colour
   inc    a                      ;; A++
   cp     palete_size            ;; Check against number of palette colours used
   jr     c, dont_reset_a        ;; If Carry (A < palette_size), do nothing
   ld     a, 1                   ;; Else, set A=1 again

dont_reset_a:
   ld    (fg_colour), a          ;; Save Foreground colour for next use

   ret                           ;; Return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; FUNC: doOneScrollStep
;;    Scrolls a complete charater line 1 byte to the left or to the right 
;; (2 mode 0 pixels)
;; INPUT: 
;;    HL: Pointer to the start of the first screen line to be scrolled (it
;; must be a pixel-0 screen line of a character)
;;     A: -1 to scroll the line to the left, other value to scroll to the right
;; DESTROYS:
;;    AF, BC, DE, HL
;;
inc_e  equ &1C   ;; Opcode for incrementing e
inc_l  equ &2C   ;; Opcode for incrementing l
_ldir_ equ &B0ED ;; Opcode for LDIR
_lddr_ equ &B8ED ;; Opcode for LDDR

doOneScrollStep:
   ;;
   ;; Set up the copy
   ;;
   
   ;; Check type of copy (-1=scroll left, scroll right otherwise)
   inc    a                ;; A++ (To check if A is -1 or not)
   jr     z, scr_left      ;; If A=-1, scroll left

scr_right:                 ;; A is not -1, scroll right
   ld     a, inc_e         ;; Increment e on scrolling right (so DE = HL + 1)
   ld    bc, screen_W-2    ;; | Add 78 bytes to point to ...
   add   hl, bc            ;; | ... the byte before the last byte of the line 
   ld    bc, _lddr_        ;; Copy instruction to use: decrementing copy (HL=>DE, DE--, HL--, BC--)
   jr    start_copy        ;; Start the copy

scr_left:
   ld     a, inc_l        ;; | Increment l on scrolling left (so HL = DE + 1)
   ld    bc, _ldir_       ;; Copy instruction to use: incrementing copy (HL=>DE, DE++, HL++, BC--)

start_copy:
   ;; Modify loop instruction that differs between movements and start
   ld   (scr_pcopy), bc    ;; | Modify internal loop code with instructions...
   ld   (scr_pincr), a     ;; | ... required for this type of copy
   
   ;;
   ;; Do the copy
   ;;
   ld     a, 8             ;; 8 pixel lines to be scrolled
loop_scroll:
   push  hl                ;; Save current hl value

   ld     d, h             ;; | DE points to the first byte...
   ld     e, l             ;; | and HL to the next one
   scr_pincr:              ;; << Memory address of the increment instruction
   inc    l                ;; | (this instruction is modified dynamically: inc l / inc e)

   ld    bc, screen_W-1    ;; 79 bytes to copy (all bytes in 1 line minus the first one)
   scr_pcopy:              ;; << Memory address of the copy instruction
   ldir                    ;; do the copy  (This instruction is modified dynamically: ldir / lddr)

   pop   hl                ;; Restore HL value, for calculations

   dec    a                ;; A-- (1 line less to be copied)
   ret    z                ;; If A==0, scroll has ended

   ;; Point to the next line to be scrolled inside this same character (HL += &800)
   ld     b, a             ;; B = A (B acts as a backup of A)
   ld     a, h             ;; | HL += &800
   add    8                ;; |
   ld     h, a             ;; |
   ld     a, b             ;; A = B (Restore A value from its backup)

   jr    loop_scroll       ;; Next line

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; FUNC: moveString
;;    Moves a string 1 byte to the left or to the right, bouncing on the
;; boundaries and then redrawing the string with a new colour
;; INPUT:
;;    IX: Pointer to a 6-bytes structure containing these fields,
;;       2 bytes > Pointer to string to be drawn
;;       1 byte  > x coordinate where the string is
;;       1 byte  > y coordinate where the string is
;;       1 byte  > current movement velocity (-1 or +1)
;;       1 byte  > max x coordinate (where it should bounce on the right side)
;; MODIFIES:
;;       byte 2: x coordinate 
;;       byte 4: movement velocity 
;; DESTROYS:
;;    AF, AF', BC, DE, HL
;;
moveString:
   ;; Update x location
   ld     d, (ix+4)               ;; D  = x velocity (VelX)
   ld     a, (ix+2)               ;; A  = x coordinate
   add    d                       ;; A2 = A + D = x + VelX

   ;; Set B=y coordinate, as this value will be used by both next branches
   ld     b, (ix+3)               ;; B = y coordinate of the string

   ;; Check whether string is touching a boundary or not
   jr     z, boundary_hit        ;; If x == 0, left boundary (1) has been exceeded
   cp    (ix+5)                  ;; Check against maxX value
   jr     c, do_string_movement  ;; If x < maxX, right boundary has not been hit

boundary_hit:
   ;; Save in C the x coordinate previous to the actual one (boundary exceeded)
   sub    d                      ;; A = A2 - D = x + VelX - VelX = x
   ld     c, a                   ;; C = x

   ;; Invert velocity (to start scrolling to the other side)
   xor    a                      ;; A = 0
   sub    d                      ;; A = -D = -VelX
   ld  (ix+4), a                   ;; Update VelX value
   
   ;; Redraw string with a new colour value
   ;; (BC already contains y and x coordinates)
   ld     a, (ix+0)              ;; | IY = Pointer to the string
   ld__iyl_a                     ;; |
   ld     a, (ix+1)              ;; |
   ld__iyh_a                     ;; |
   call  redrawString            ;; Redraws the string

   ret                           ;; Nothing more to do, return.

do_string_movement:
   ;; Update string's x location
   ld (ix+2), a                   ;; Update x location value

   ;; Save VelX into a'
   ld     a, d                   ;; A = D = VelX
   ex    af, af'                 ;; A' = VelX

   ;; Calculate memory location for y line
   ;; (B already contains y coordinate)
   ld     c, 0                  ;; C = 0 (x coordinate = 0 to get the start of the y line)
   ld    de, pvideomem          ;; DE points to the start of video memory
   call  cpct_getScreenPtr      ;; Return pointer to byte located at (x,y) (C, B) in HL
   ;; HL now points to the start of the first pixel line where the
   ;; string is located (to be able to scroll it)

   ;; Scroll the string
   ;; (HL already points to the start of the first pixel line to be scrolled)
   ex    af, af'                 ;; A = VelX (recover value from A')
   call  doOneScrollStep         ;; Do scroll to the side determined by VelX

   ret                           ;; Return


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MAIN function. This is the entry point of the application.
;;
main: 
   call  init                 ;; Initialize the CPC
   call  moveSprite           ;; Do the complete sprite animation and return when finished

   ;; Draw octopusjig string
   ld    iy, str_dav          ;; IY points to @octopusjig string
   ld    bc, xy_str_dav       ;; BC = y, x coordinates where to draw @octopusjig string
   call  redrawString         ;; Draw the string with the initial colour

loop:
   ;; Scroll Happy String
   ld    ix, tscroll_happy   ;; IX points to the structure with scroll information about "Happy"
   call  cpct_waitVSYNC      ;; Wait for VSYNC before proceeding
   call  moveString          ;; Move "Happy" String

   ;; Scroll BDay String
   ld    ix, tscroll_bday    ;; IX points to the structure with scroll information about "Birthday"
   call  cpct_waitVSYNC      ;; Wait for VSYNC before proceeding
   call  moveString          ;; Move "Birthday" String

   jr    loop                ;; Repeat forever

; Data created with Img2CPC - (c) Retroworks - 2007-2017
; Palette (16 entries) uses hardware values.
g_palette: db &5f, &54, &5c, &58, &56, &46, &57, &5e, &40, &47, &5b, &4b, &4c, &4e, &52, &4a

; Tile g_octopusjig: 9&133 pixels, 45x133 bytes.
g_octopusjig: ; defs 45 * 133
	db &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00
	db &00, &00, &d0, &d0, &d0, &81, &f4, &52, &f8, &f8, &d4, &a1, &81, &03, &ed, &03, &03, &03, &03, &81, &03, &c0, &03, &8b, &8b, &8b, &03, &03, &42, &d0, &f8, &e8, &a9, &90, &d0, &f8, &f8, &a9, &42, &03, &81, &03, &03, &00, &00
	db &00, &40, &e8, &e0, &42, &ed, &03, &56, &d0, &81, &f8, &42, &03, &47, &cb, &8b, &03, &03, &03, &03, &03, &81, &03, &8b, &47, &47, &cf, &03, &03, &42, &42, &e0, &a1, &e0, &03, &f4, &56, &e0, &42, &42, &56, &03, &a9, &02, &00
	db &00, &e0, &e0, &42, &a1, &03, &8b, &52, &d4, &f0, &a9, &e8, &03, &e9, &de, &8b, &de, &8b, &8b, &03, &03, &03, &47, &47, &c7, &8b, &cf, &a9, &03, &03, &03, &d4, &81, &d4, &81, &d0, &81, &a9, &42, &42, &52, &81, &03, &03, &00
	db &40, &e0, &d0, &c0, &03, &56, &43, &03, &21, &d4, &f0, &42, &03, &47, &47, &d6, &03, &03, &cf, &cf, &47, &cf, &cb, &8b, &cf, &47, &cf, &8b, &03, &03, &47, &42, &03, &d0, &d0, &d4, &e0, &42, &42, &56, &56, &f8, &56, &03, &02
	db &40, &42, &42, &e0, &81, &03, &43, &03, &52, &d4, &81, &81, &03, &ed, &a9, &8b, &8b, &03, &03, &47, &47, &47, &47, &47, &47, &c7, &47, &c7, &8b, &cf, &cf, &8b, &42, &42, &42, &42, &03, &56, &42, &e0, &52, &56, &a1, &03, &02
	db &54, &d0, &d0, &81, &03, &03, &47, &56, &56, &f0, &42, &a1, &56, &8b, &8b, &47, &47, &47, &cb, &47, &c7, &47, &c7, &47, &c7, &03, &cf, &8b, &c7, &47, &8b, &8b, &03, &81, &e0, &e0, &e0, &52, &81, &d4, &fc, &42, &56, &03, &02
	db &40, &e0, &e8, &e0, &03, &a9, &56, &8b, &e0, &12, &42, &81, &03, &47, &ed, &03, &cf, &8b, &8b, &47, &47, &47, &43, &03, &03, &47, &47, &cf, &ed, &47, &c7, &03, &03, &03, &03, &81, &d4, &42, &03, &d0, &52, &e8, &a1, &56, &02
	db &54, &d0, &d0, &d0, &03, &03, &47, &56, &42, &e0, &81, &47, &47, &cb, &8b, &cf, &cf, &cf, &47, &83, &cb, &03, &03, &56, &43, &47, &8b, &8b, &83, &8b, &03, &83, &03, &03, &42, &e0, &e0, &03, &81, &81, &d4, &81, &56, &03, &02
	db &50, &81, &d0, &c0, &03, &a9, &a9, &8b, &a9, &03, &81, &43, &8b, &47, &cf, &8b, &cf, &cf, &47, &03, &03, &cb, &8b, &03, &56, &47, &c7, &8b, &83, &8b, &03, &03, &c7, &8b, &8b, &03, &81, &81, &81, &42, &a1, &e0, &03, &56, &02
	db &40, &e0, &d0, &81, &03, &03, &03, &8b, &8b, &03, &47, &cf, &cf, &cf, &c7, &47, &83, &03, &03, &56, &47, &47, &43, &43, &03, &83, &8b, &03, &56, &06, &42, &03, &03, &03, &8b, &47, &03, &03, &81, &81, &42, &56, &03, &42, &02
	db &40, &e0, &42, &e0, &03, &03, &a9, &a9, &47, &03, &03, &56, &43, &8b, &cf, &47, &cb, &03, &09, &03, &83, &a9, &03, &42, &03, &56, &cf, &cb, &03, &81, &48, &42, &03, &83, &47, &03, &03, &03, &03, &42, &03, &81, &56, &03, &02
	db &01, &d4, &d0, &03, &03, &a9, &03, &47, &47, &47, &8b, &03, &47, &ed, &47, &a9, &a9, &03, &03, &83, &03, &06, &42, &09, &84, &03, &43, &03, &8b, &03, &42, &06, &42, &03, &43, &03, &83, &03, &03, &42, &03, &f4, &03, &03, &a8
	db &50, &52, &d0, &81, &03, &03, &a9, &47, &03, &43, &47, &83, &03, &47, &c7, &03, &83, &4d, &8b, &03, &03, &42, &03, &42, &03, &09, &03, &03, &83, &03, &42, &42, &03, &03, &03, &03, &03, &03, &03, &42, &42, &03, &03, &03, &02
	db &40, &03, &42, &52, &a9, &03, &03, &43, &cf, &47, &cf, &06, &47, &03, &8b, &83, &03, &cf, &03, &06, &03, &09, &06, &81, &09, &03, &03, &03, &03, &c7, &03, &03, &81, &09, &03, &03, &03, &03, &03, &03, &03, &47, &cf, &03, &02
	db &40, &e0, &f4, &81, &03, &03, &03, &cf, &8b, &03, &03, &42, &83, &43, &cf, &cf, &8b, &83, &03, &03, &81, &09, &8b, &8b, &03, &81, &83, &42, &03, &03, &8b, &81, &42, &c0, &81, &09, &03, &c7, &03, &03, &cf, &cf, &cf, &cf, &8a
	db &01, &56, &a1, &03, &56, &8b, &47, &cf, &8b, &8b, &43, &47, &03, &03, &cf, &cf, &cf, &8b, &09, &06, &03, &47, &8b, &42, &c0, &03, &81, &09, &48, &43, &03, &03, &03, &03, &03, &81, &81, &03, &cf, &47, &47, &cf, &cf, &cf, &8a
	db &50, &42, &f8, &03, &03, &8b, &47, &47, &47, &83, &8b, &cb, &8b, &47, &cf, &cf, &47, &8b, &56, &03, &a9, &03, &03, &09, &c0, &81, &81, &c0, &42, &03, &06, &03, &03, &03, &42, &06, &03, &03, &03, &cf, &8b, &47, &cf, &8b, &80
	db &01, &52, &81, &e8, &03, &47, &cf, &8b, &03, &47, &03, &03, &cb, &47, &47, &83, &43, &03, &03, &06, &03, &48, &81, &c0, &81, &c0, &03, &81, &81, &81, &81, &06, &81, &03, &81, &42, &c0, &03, &42, &47, &47, &47, &cf, &03, &80
	db &40, &03, &a1, &a1, &03, &8b, &8b, &cb, &03, &03, &8b, &83, &47, &c7, &cf, &56, &8b, &03, &83, &03, &42, &42, &c0, &84, &c0, &c0, &c0, &c0, &84, &81, &c0, &42, &42, &03, &42, &03, &81, &84, &03, &c5, &03, &03, &cf, &8b, &80
	db &01, &81, &81, &56, &03, &cf, &cb, &03, &06, &03, &47, &56, &8b, &de, &8b, &03, &03, &83, &03, &48, &42, &c0, &c0, &c0, &81, &c0, &c0, &c0, &42, &c0, &c0, &c0, &84, &c0, &03, &03, &03, &81, &42, &09, &03, &03, &47, &03, &02
	db &40, &a1, &52, &03, &03, &cf, &47, &03, &03, &43, &03, &47, &83, &43, &cf, &43, &03, &03, &d0, &48, &42, &42, &c0, &c0, &c0, &c0, &c0, &c0, &c0, &c0, &c0, &42, &42, &42, &03, &09, &84, &81, &81, &c0, &03, &8b, &03, &03, &02
	db &01, &81, &81, &03, &47, &83, &03, &47, &43, &cf, &03, &48, &56, &cf, &47, &56, &06, &03, &48, &42, &42, &c0, &c0, &c0, &c0, &42, &c0, &c0, &c0, &c0, &c0, &c0, &42, &42, &81, &c0, &42, &42, &48, &42, &83, &c5, &03, &03, &02
	db &40, &52, &81, &03, &cf, &03, &83, &83, &47, &56, &03, &03, &83, &de, &cb, &03, &03, &81, &81, &81, &48, &42, &c0, &c0, &c0, &81, &c0, &c0, &42, &c0, &c0, &c0, &c0, &42, &c0, &42, &81, &c0, &42, &42, &03, &03, &03, &a1, &02
	db &50, &81, &42, &03, &47, &47, &03, &03, &03, &83, &42, &09, &03, &47, &47, &06, &03, &09, &06, &81, &81, &c0, &42, &c0, &c0, &c0, &c0, &42, &c0, &c0, &c0, &c0, &c0, &81, &c0, &81, &c0, &81, &c0, &42, &83, &03, &03, &03, &02
	db &40, &e0, &a1, &03, &47, &83, &e9, &06, &03, &03, &42, &03, &06, &43, &03, &56, &03, &03, &42, &42, &c0, &42, &c0, &c0, &81, &c0, &c0, &c0, &81, &c0, &81, &c0, &c0, &c0, &42, &c0, &81, &c0, &c0, &81, &81, &03, &03, &03, &02
	db &40, &03, &c0, &03, &47, &03, &03, &03, &84, &84, &81, &81, &c5, &56, &43, &03, &03, &06, &42, &06, &42, &42, &42, &c0, &c0, &c0, &c0, &c0, &c0, &81, &c0, &81, &c0, &c0, &c0, &42, &42, &c0, &42, &81, &06, &42, &03, &03, &02
	db &01, &d0, &42, &03, &47, &03, &09, &03, &42, &42, &81, &06, &03, &cf, &47, &03, &83, &03, &09, &42, &42, &c8, &42, &42, &c0, &c0, &c0, &42, &42, &81, &81, &c0, &42, &42, &42, &c0, &c0, &c0, &42, &c0, &c0, &03, &03, &03, &02
	db &40, &e0, &03, &43, &83, &83, &56, &09, &c0, &c0, &48, &03, &e9, &03, &83, &c7, &03, &03, &03, &09, &81, &81, &c0, &c8, &81, &c4, &c0, &c0, &81, &c0, &42, &42, &48, &84, &81, &c0, &c0, &c0, &c0, &42, &42, &81, &42, &03, &02
	db &54, &81, &81, &8b, &cf, &03, &03, &81, &09, &81, &c0, &09, &03, &42, &03, &56, &8b, &83, &03, &06, &03, &81, &c0, &42, &c0, &42, &42, &03, &81, &81, &84, &03, &42, &03, &81, &81, &c0, &81, &c0, &c0, &81, &c0, &81, &03, &02
	db &40, &e0, &a9, &47, &56, &8b, &06, &42, &42, &c0, &42, &03, &06, &81, &42, &83, &03, &03, &03, &03, &81, &c8, &42, &42, &42, &81, &81, &81, &c1, &81, &42, &42, &09, &81, &48, &42, &c0, &c0, &81, &c0, &c0, &42, &03, &03, &02
	db &40, &42, &03, &cf, &83, &83, &42, &03, &09, &09, &42, &c0, &81, &c0, &03, &03, &83, &83, &06, &03, &81, &42, &42, &c0, &42, &42, &48, &06, &03, &06, &06, &03, &43, &81, &03, &09, &42, &c0, &c0, &c0, &c0, &c0, &81, &81, &02
	db &40, &e0, &03, &83, &47, &47, &03, &42, &03, &03, &c2, &81, &81, &09, &84, &03, &03, &03, &03, &06, &81, &03, &c0, &42, &09, &09, &03, &42, &06, &03, &03, &06, &03, &06, &81, &81, &c0, &c0, &c0, &c0, &c8, &42, &42, &03, &02
	db &40, &42, &56, &8b, &d6, &03, &06, &42, &43, &a9, &03, &c0, &81, &81, &42, &06, &43, &43, &03, &03, &c0, &81, &c0, &81, &81, &81, &81, &09, &03, &89, &09, &03, &09, &03, &06, &06, &42, &42, &c0, &c0, &c0, &c0, &c0, &81, &02
	db &40, &e0, &03, &cf, &03, &09, &81, &06, &81, &43, &c0, &48, &42, &06, &06, &03, &03, &03, &06, &03, &09, &c0, &06, &42, &06, &06, &03, &03, &09, &03, &03, &09, &03, &09, &03, &81, &81, &c0, &c0, &c0, &c0, &c8, &42, &42, &02
	db &40, &42, &03, &a9, &09, &06, &42, &81, &c0, &03, &42, &42, &48, &42, &42, &03, &09, &09, &03, &46, &03, &48, &42, &09, &81, &03, &06, &03, &06, &06, &03, &06, &03, &81, &09, &06, &42, &42, &c0, &c0, &c0, &c0, &c0, &c0, &02
	db &40, &c0, &03, &03, &42, &03, &03, &42, &c0, &48, &03, &c0, &03, &09, &03, &09, &03, &03, &09, &03, &81, &42, &09, &03, &09, &09, &09, &06, &03, &03, &06, &03, &06, &03, &06, &42, &06, &81, &81, &c0, &42, &42, &c0, &81, &a8
	db &40, &03, &43, &03, &06, &03, &09, &c0, &42, &c0, &42, &42, &81, &06, &03, &03, &09, &03, &06, &06, &06, &03, &81, &09, &03, &03, &03, &03, &03, &09, &03, &09, &06, &06, &03, &09, &81, &42, &81, &c0, &c0, &81, &c0, &c0, &02
	db &01, &03, &cf, &43, &81, &d4, &42, &c0, &c0, &c0, &c0, &42, &42, &03, &06, &03, &03, &09, &03, &03, &03, &09, &83, &03, &09, &09, &09, &09, &09, &03, &09, &03, &09, &03, &81, &03, &09, &81, &c0, &c0, &c0, &c0, &c0, &c0, &02
	db &40, &03, &8b, &56, &06, &03, &09, &42, &c0, &c0, &c0, &81, &81, &09, &03, &03, &03, &03, &09, &06, &03, &03, &81, &09, &03, &03, &03, &03, &06, &03, &06, &03, &06, &06, &06, &03, &c1, &81, &81, &c0, &c0, &c0, &c0, &c0, &02
	db &40, &03, &43, &03, &03, &03, &81, &c0, &c0, &c0, &42, &48, &03, &03, &06, &03, &09, &03, &46, &03, &09, &09, &09, &03, &09, &09, &09, &09, &03, &09, &81, &09, &03, &06, &42, &06, &03, &81, &c0, &c0, &c0, &c0, &81, &81, &02
	db &40, &4d, &03, &a9, &48, &09, &c0, &42, &c0, &c0, &c0, &42, &c0, &09, &03, &89, &03, &09, &06, &03, &03, &03, &06, &03, &46, &03, &03, &03, &09, &03, &09, &06, &06, &03, &06, &03, &81, &09, &03, &c0, &c0, &c0, &c0, &03, &8a
	db &40, &03, &03, &09, &81, &c0, &48, &c0, &c0, &c0, &c0, &81, &03, &03, &06, &03, &81, &03, &81, &06, &42, &06, &03, &84, &03, &09, &09, &09, &06, &06, &42, &03, &81, &09, &09, &06, &03, &81, &c0, &c0, &c0, &c0, &03, &29, &02
	db &01, &47, &ca, &03, &e8, &42, &81, &c0, &c0, &c0, &42, &c0, &c4, &03, &03, &03, &06, &03, &09, &03, &09, &03, &09, &03, &09, &03, &03, &06, &03, &03, &06, &06, &03, &81, &e8, &42, &06, &06, &03, &42, &c0, &c0, &81, &a1, &02
	db &01, &83, &03, &c2, &48, &c0, &c0, &c0, &c0, &c0, &c0, &06, &03, &03, &09, &09, &03, &03, &46, &03, &46, &42, &03, &09, &42, &09, &09, &03, &09, &09, &03, &81, &09, &09, &c1, &06, &42, &03, &c0, &c0, &c0, &c0, &c0, &03, &02
	db &01, &47, &8b, &03, &03, &42, &c0, &c0, &c8, &c0, &c0, &c0, &84, &03, &03, &03, &81, &09, &03, &09, &03, &09, &03, &06, &03, &03, &06, &03, &03, &06, &06, &03, &42, &03, &d4, &03, &03, &09, &03, &42, &c0, &c0, &c0, &81, &02
	db &01, &83, &cb, &03, &48, &c0, &c0, &c0, &c0, &c0, &81, &81, &03, &03, &46, &06, &03, &03, &09, &03, &09, &46, &42, &03, &89, &09, &89, &06, &42, &03, &03, &84, &03, &09, &09, &84, &81, &81, &48, &c0, &c0, &c0, &c0, &c0, &80
	db &01, &03, &43, &03, &42, &42, &42, &42, &c0, &c0, &c0, &c0, &81, &06, &03, &03, &46, &03, &03, &03, &03, &06, &03, &09, &03, &81, &46, &03, &43, &81, &09, &42, &03, &81, &09, &03, &06, &42, &03, &46, &c0, &c0, &c0, &c0, &80
	db &01, &09, &8b, &c2, &81, &c0, &c0, &c0, &c0, &c0, &81, &81, &09, &03, &06, &03, &09, &42, &06, &03, &09, &03, &46, &03, &09, &06, &03, &06, &03, &03, &03, &06, &03, &03, &81, &09, &81, &06, &42, &c0, &c0, &c0, &c0, &c0, &02
	db &01, &06, &03, &81, &09, &81, &c0, &c0, &c0, &c0, &c0, &c0, &42, &03, &03, &03, &06, &03, &03, &89, &03, &09, &03, &03, &03, &03, &09, &03, &09, &89, &09, &03, &06, &03, &03, &03, &09, &81, &09, &81, &c0, &c0, &c0, &c0, &02
	db &01, &81, &84, &81, &47, &c0, &c0, &c0, &c0, &c0, &42, &03, &09, &06, &46, &03, &03, &46, &03, &03, &03, &03, &09, &09, &89, &09, &03, &89, &03, &03, &89, &09, &03, &06, &42, &09, &03, &42, &42, &42, &c0, &c0, &c0, &c0, &02
	db &01, &48, &03, &c0, &47, &42, &42, &c0, &c0, &c0, &c0, &81, &03, &03, &03, &03, &89, &03, &03, &09, &06, &03, &03, &06, &03, &03, &09, &03, &09, &09, &03, &06, &06, &03, &03, &42, &06, &03, &09, &81, &c0, &c0, &c0, &c0, &02
	db &01, &c0, &42, &06, &81, &42, &c0, &c0, &c0, &c0, &03, &09, &81, &03, &03, &03, &03, &06, &03, &46, &03, &06, &06, &03, &09, &09, &03, &09, &03, &06, &06, &03, &03, &09, &09, &06, &03, &81, &81, &81, &c0, &c0, &c0, &c0, &02
	db &01, &ca, &09, &42, &03, &42, &03, &c0, &c0, &c0, &81, &81, &03, &03, &03, &03, &03, &03, &03, &06, &43, &03, &03, &09, &03, &09, &09, &06, &06, &03, &03, &09, &09, &03, &09, &03, &03, &03, &09, &81, &c0, &c0, &c0, &c0, &a0
	db &01, &03, &81, &03, &03, &81, &42, &c0, &c0, &c0, &03, &09, &03, &03, &03, &09, &46, &03, &09, &03, &06, &06, &43, &06, &43, &03, &09, &03, &43, &06, &06, &03, &09, &09, &06, &06, &06, &03, &81, &81, &c0, &c0, &c0, &81, &02
	db &01, &43, &03, &43, &42, &42, &81, &c4, &c0, &c0, &42, &03, &06, &03, &03, &03, &09, &81, &84, &06, &03, &06, &03, &83, &09, &83, &09, &09, &09, &43, &03, &83, &09, &06, &03, &03, &42, &03, &03, &81, &c0, &c0, &c0, &d4, &a0
	db &45, &03, &43, &03, &42, &03, &03, &c0, &c0, &42, &03, &03, &03, &03, &89, &81, &06, &03, &09, &81, &09, &09, &09, &09, &06, &03, &83, &09, &06, &06, &06, &03, &83, &09, &09, &48, &c2, &06, &81, &81, &c0, &c0, &c0, &81, &a8
	db &45, &8b, &03, &03, &09, &84, &81, &c0, &c0, &81, &06, &03, &03, &03, &03, &c2, &06, &81, &81, &c0, &81, &81, &56, &06, &43, &ac, &03, &09, &09, &83, &a9, &5c, &06, &03, &09, &03, &09, &81, &81, &81, &c0, &c0, &c0, &52, &a8
	db &45, &8b, &03, &09, &81, &81, &c0, &42, &42, &03, &03, &03, &06, &06, &42, &06, &42, &c2, &48, &09, &84, &84, &c1, &56, &06, &43, &e9, &56, &83, &09, &83, &06, &03, &48, &42, &48, &42, &c2, &42, &42, &c0, &c0, &c0, &03, &a0
	db &45, &8b, &03, &03, &42, &81, &81, &81, &81, &81, &03, &03, &03, &03, &09, &84, &06, &06, &03, &84, &81, &c0, &84, &06, &56, &03, &09, &09, &09, &ac, &ac, &56, &09, &c0, &81, &84, &06, &42, &09, &81, &c0, &c0, &c0, &56, &02
	db &45, &8b, &09, &09, &09, &c0, &c0, &c0, &81, &03, &03, &09, &42, &42, &06, &03, &81, &81, &84, &c0, &48, &09, &c0, &84, &06, &d6, &09, &d6, &06, &03, &06, &c0, &c0, &48, &48, &42, &42, &09, &81, &81, &c0, &c0, &81, &03, &a8
	db &45, &8b, &8b, &42, &c0, &c0, &c0, &42, &c0, &09, &03, &03, &03, &09, &09, &09, &0c, &84, &42, &42, &42, &48, &09, &09, &81, &09, &ac, &06, &a9, &0c, &42, &06, &c0, &42, &42, &48, &48, &06, &06, &81, &c0, &c0, &81, &03, &a8
	db &45, &cf, &03, &83, &48, &c0, &81, &81, &03, &03, &03, &06, &03, &09, &06, &c0, &03, &81, &c0, &c0, &81, &81, &48, &84, &a9, &09, &09, &06, &06, &a9, &48, &81, &84, &c0, &48, &42, &06, &06, &42, &42, &c0, &c0, &03, &f4, &02
	db &45, &cf, &03, &03, &09, &42, &42, &81, &c0, &89, &03, &03, &03, &06, &56, &48, &42, &48, &c0, &48, &84, &42, &48, &06, &81, &09, &5c, &d6, &06, &a9, &48, &09, &c0, &c0, &c0, &48, &c0, &d4, &09, &09, &42, &c0, &03, &07, &80
	db &45, &cf, &83, &09, &09, &48, &42, &81, &81, &03, &06, &06, &06, &e8, &e8, &42, &48, &03, &48, &42, &03, &03, &84, &42, &09, &06, &03, &09, &09, &84, &d4, &81, &84, &42, &03, &42, &48, &09, &09, &81, &c0, &c0, &03, &56, &a8
	db &45, &cf, &03, &81, &09, &09, &81, &81, &81, &09, &03, &03, &81, &06, &06, &81, &c0, &42, &42, &c0, &03, &48, &48, &09, &84, &03, &09, &03, &09, &e8, &48, &09, &c0, &48, &d4, &42, &42, &c0, &a9, &09, &42, &c0, &e5, &8b, &a0
	db &45, &47, &8b, &09, &83, &81, &c0, &81, &81, &03, &03, &06, &06, &42, &06, &06, &03, &84, &06, &06, &84, &42, &e8, &06, &d4, &81, &06, &56, &06, &81, &48, &42, &09, &81, &48, &48, &09, &09, &48, &81, &81, &c0, &81, &03, &a8
	db &01, &03, &03, &03, &86, &06, &03, &c0, &09, &43, &03, &03, &03, &09, &03, &81, &09, &42, &42, &56, &81, &09, &48, &42, &06, &06, &03, &06, &03, &48, &56, &48, &06, &06, &03, &09, &d4, &81, &81, &09, &81, &c0, &81, &0b, &02
	db &01, &03, &47, &03, &06, &03, &42, &81, &81, &03, &03, &03, &03, &81, &09, &81, &06, &06, &06, &06, &06, &42, &09, &48, &42, &03, &06, &03, &84, &06, &84, &06, &06, &06, &06, &06, &06, &06, &42, &42, &03, &c0, &03, &03, &a0
	db &01, &47, &03, &8b, &43, &06, &06, &81, &c1, &43, &43, &03, &09, &42, &03, &48, &42, &09, &09, &09, &e8, &09, &81, &09, &48, &09, &03, &03, &03, &81, &e8, &42, &e8, &06, &56, &06, &81, &84, &06, &06, &81, &c0, &03, &03, &20
	db &45, &03, &cf, &03, &83, &03, &09, &c0, &03, &43, &8b, &8b, &06, &06, &06, &03, &09, &81, &84, &84, &81, &09, &09, &81, &03, &03, &09, &09, &09, &09, &09, &09, &09, &09, &84, &81, &48, &42, &42, &42, &03, &c0, &81, &03, &02
	db &01, &8b, &8b, &8b, &09, &c2, &81, &c0, &09, &03, &83, &83, &03, &03, &03, &81, &81, &09, &81, &03, &09, &81, &81, &06, &84, &03, &89, &03, &09, &81, &48, &06, &42, &09, &09, &48, &06, &06, &06, &06, &81, &42, &03, &52, &02
	db &45, &8b, &03, &03, &03, &43, &42, &42, &03, &83, &47, &03, &09, &09, &c1, &03, &09, &81, &09, &81, &06, &06, &06, &03, &03, &03, &03, &81, &42, &09, &06, &42, &03, &42, &42, &03, &81, &81, &81, &81, &81, &c0, &03, &03, &02
	db &45, &8b, &03, &03, &83, &06, &06, &03, &81, &03, &83, &83, &03, &03, &03, &46, &03, &03, &03, &09, &81, &03, &42, &09, &81, &09, &89, &06, &03, &09, &81, &09, &09, &09, &09, &09, &09, &09, &09, &09, &09, &81, &03, &42, &02
	db &01, &8b, &03, &03, &03, &83, &42, &06, &03, &03, &47, &03, &03, &09, &89, &03, &4c, &06, &46, &03, &09, &48, &83, &03, &09, &42, &03, &89, &42, &06, &06, &03, &09, &03, &81, &c4, &42, &06, &81, &81, &81, &81, &81, &03, &a0
	db &01, &03, &03, &03, &03, &43, &83, &03, &09, &83, &43, &43, &03, &03, &06, &03, &03, &03, &06, &03, &09, &03, &06, &03, &89, &06, &03, &03, &09, &42, &03, &09, &06, &06, &43, &06, &06, &03, &09, &09, &09, &81, &81, &03, &02
	db &01, &03, &81, &42, &03, &83, &06, &03, &03, &06, &8b, &03, &06, &06, &03, &8c, &06, &89, &09, &06, &03, &09, &09, &81, &03, &03, &89, &81, &42, &09, &09, &a9, &09, &06, &42, &03, &09, &09, &48, &42, &42, &42, &42, &c0, &80
	db &01, &89, &03, &89, &03, &83, &83, &06, &06, &03, &43, &06, &03, &03, &09, &03, &03, &09, &46, &06, &06, &03, &09, &c8, &09, &03, &03, &89, &03, &03, &c0, &09, &06, &43, &06, &06, &03, &06, &06, &06, &42, &c0, &03, &94, &80
	db &01, &03, &03, &03, &03, &8b, &cb, &03, &81, &06, &56, &03, &03, &03, &06, &06, &06, &06, &06, &03, &06, &42, &42, &03, &46, &06, &03, &06, &06, &42, &83, &84, &06, &06, &03, &09, &0c, &06, &06, &42, &42, &42, &42, &c0, &80
	db &01, &89, &47, &cf, &cf, &cf, &8b, &83, &06, &03, &03, &09, &09, &09, &03, &03, &09, &03, &06, &06, &06, &c2, &09, &c8, &03, &03, &46, &03, &89, &03, &81, &03, &09, &06, &06, &03, &06, &03, &09, &0c, &42, &81, &03, &81, &80
	db &01, &cf, &cf, &cf, &cb, &cf, &8e, &03, &03, &09, &09, &03, &03, &03, &09, &09, &83, &0c, &43, &06, &03, &09, &09, &03, &46, &46, &06, &03, &06, &06, &06, &06, &06, &09, &83, &0c, &06, &06, &56, &42, &42, &42, &c0, &c0, &80
	db &45, &cf, &8b, &83, &06, &cf, &cb, &43, &03, &03, &03, &09, &09, &83, &06, &03, &09, &83, &09, &09, &49, &81, &09, &06, &06, &03, &06, &06, &03, &09, &81, &06, &03, &09, &09, &83, &09, &09, &09, &0c, &42, &03, &81, &81, &80
	db &41, &43, &06, &06, &84, &cf, &8b, &43, &cb, &06, &43, &03, &06, &06, &03, &09, &09, &09, &09, &5c, &06, &06, &03, &09, &03, &09, &09, &06, &06, &43, &09, &09, &5c, &09, &09, &09, &e9, &ac, &06, &42, &03, &c0, &c8, &c0, &80
	db &01, &06, &06, &06, &06, &47, &cf, &56, &8b, &03, &03, &06, &03, &03, &83, &09, &09, &e9, &a9, &09, &09, &09, &09, &09, &09, &09, &06, &43, &06, &06, &56, &03, &09, &09, &5c, &09, &09, &09, &ac, &ac, &81, &42, &81, &81, &80
	db &01, &09, &09, &09, &48, &09, &83, &83, &83, &83, &09, &09, &06, &06, &03, &09, &83, &09, &49, &ac, &56, &06, &06, &06, &06, &06, &06, &a9, &09, &ac, &06, &09, &5c, &06, &06, &06, &06, &06, &06, &42, &42, &c0, &42, &c0, &80
	db &01, &03, &84, &84, &06, &06, &a9, &d6, &cf, &03, &03, &09, &06, &03, &5c, &06, &ac, &56, &09, &09, &0c, &03, &09, &09, &48, &06, &06, &56, &09, &84, &42, &a9, &09, &5c, &d6, &5c, &d6, &09, &ac, &06, &81, &c0, &42, &81, &80
	db &45, &cb, &03, &09, &09, &09, &09, &09, &d6, &83, &83, &03, &09, &09, &06, &06, &43, &09, &5c, &06, &03, &09, &81, &09, &d4, &09, &06, &06, &06, &e8, &09, &09, &06, &03, &09, &09, &09, &09, &09, &ac, &42, &81, &c0, &c0, &80
	db &45, &cf, &cf, &8e, &09, &09, &48, &42, &47, &ed, &03, &09, &03, &09, &09, &09, &09, &ac, &06, &56, &09, &09, &09, &81, &09, &84, &56, &56, &06, &03, &09, &84, &81, &5c, &06, &56, &5c, &56, &48, &06, &81, &c0, &06, &81, &80
	db &45, &03, &83, &43, &03, &81, &81, &84, &43, &43, &a9, &06, &56, &06, &56, &56, &09, &09, &ac, &06, &42, &42, &42, &09, &d4, &09, &84, &06, &42, &e8, &42, &03, &09, &81, &09, &09, &09, &09, &5c, &42, &42, &c0, &c0, &42, &80
	db &04, &06, &06, &06, &06, &81, &09, &c0, &47, &47, &83, &03, &06, &03, &09, &09, &d6, &09, &09, &81, &06, &06, &42, &06, &42, &56, &d4, &81, &09, &48, &ac, &81, &81, &09, &d4, &56, &5c, &5c, &06, &09, &09, &81, &c0, &48, &02
	db &01, &03, &03, &09, &43, &42, &42, &48, &09, &d6, &8e, &06, &03, &09, &09, &5c, &09, &a9, &09, &09, &81, &81, &81, &81, &84, &06, &42, &06, &81, &06, &42, &ac, &56, &d4, &06, &06, &03, &09, &09, &e8, &c0, &42, &81, &c0, &80
	db &04, &43, &03, &09, &0c, &06, &81, &c0, &03, &8b, &03, &06, &06, &56, &06, &03, &09, &5c, &d4, &56, &09, &09, &09, &09, &03, &81, &5c, &81, &ac, &81, &09, &42, &06, &06, &06, &56, &09, &5c, &06, &43, &84, &81, &c0, &42, &02
	db &01, &06, &03, &09, &09, &09, &09, &09, &84, &83, &d6, &03, &06, &06, &56, &5c, &09, &09, &06, &81, &42, &03, &09, &06, &ac, &09, &09, &09, &09, &09, &09, &5c, &09, &56, &d4, &09, &5c, &06, &06, &e8, &42, &81, &d4, &84, &80
	db &01, &03, &09, &03, &06, &03, &48, &81, &81, &a9, &8e, &06, &03, &06, &06, &03, &a9, &5c, &06, &06, &ac, &42, &06, &06, &03, &48, &09, &48, &09, &48, &09, &09, &48, &09, &09, &a9, &09, &5c, &06, &06, &42, &84, &c0, &42, &02
	db &01, &09, &06, &06, &06, &43, &06, &06, &c0, &83, &03, &09, &0c, &03, &09, &09, &09, &ac, &56, &81, &42, &09, &48, &09, &48, &09, &48, &09, &09, &09, &48, &06, &84, &d4, &48, &09, &ac, &06, &06, &e8, &c0, &42, &42, &e8, &80
	db &01, &42, &03, &09, &06, &43, &06, &42, &42, &09, &83, &03, &06, &06, &03, &5c, &06, &06, &06, &48, &48, &48, &06, &81, &48, &06, &06, &42, &09, &84, &84, &81, &81, &09, &56, &06, &a9, &5c, &06, &06, &42, &c0, &81, &81, &80
	db &04, &43, &03, &06, &03, &09, &06, &06, &81, &81, &56, &09, &09, &ac, &06, &06, &56, &56, &81, &09, &81, &84, &81, &48, &8c, &c0, &48, &48, &06, &81, &09, &48, &09, &d4, &09, &09, &06, &06, &ac, &42, &c0, &06, &81, &84, &02
	db &01, &03, &09, &06, &03, &5c, &09, &09, &06, &42, &03, &06, &06, &03, &09, &a9, &09, &09, &5c, &06, &06, &03, &c4, &09, &81, &83, &89, &06, &06, &42, &48, &06, &06, &06, &06, &ac, &56, &09, &06, &a9, &42, &81, &c0, &e8, &02
	db &04, &03, &06, &03, &09, &06, &06, &06, &42, &06, &06, &03, &09, &5c, &06, &09, &ac, &56, &06, &03, &03, &09, &09, &c4, &09, &48, &0c, &c4, &84, &06, &06, &42, &06, &56, &06, &56, &09, &ac, &e8, &c0, &81, &c0, &42, &81, &80
	db &01, &06, &03, &03, &09, &09, &06, &06, &06, &81, &81, &81, &09, &06, &03, &06, &56, &09, &09, &09, &09, &03, &43, &42, &09, &09, &09, &09, &09, &48, &06, &06, &a9, &5c, &06, &06, &06, &03, &09, &c0, &42, &48, &42, &48, &02
	db &04, &03, &06, &06, &03, &09, &09, &09, &09, &81, &84, &06, &06, &06, &06, &09, &09, &5c, &56, &09, &06, &06, &03, &09, &06, &06, &06, &06, &06, &06, &03, &a9, &09, &42, &5c, &56, &5c, &5c, &81, &c0, &42, &42, &d4, &c0, &80
	db &01, &06, &03, &06, &03, &09, &06, &06, &84, &81, &c0, &81, &09, &ac, &56, &09, &a9, &09, &09, &06, &42, &03, &09, &06, &03, &09, &09, &09, &09, &06, &06, &d4, &06, &a9, &09, &09, &09, &09, &48, &c0, &c0, &81, &c0, &81, &80
	db &04, &03, &06, &03, &06, &06, &56, &09, &c2, &42, &c0, &09, &84, &03, &09, &ac, &06, &56, &81, &09, &06, &06, &03, &09, &09, &06, &03, &09, &06, &a9, &09, &ac, &06, &06, &56, &d4, &09, &d4, &c0, &42, &c0, &42, &e8, &42, &80
	db &01, &09, &03, &06, &03, &03, &09, &06, &ac, &42, &c0, &42, &06, &06, &06, &06, &a9, &09, &5c, &06, &56, &03, &09, &03, &ac, &06, &a9, &5c, &06, &56, &09, &06, &03, &e8, &06, &42, &ac, &81, &c0, &81, &c0, &c0, &42, &48, &80
	db &01, &03, &09, &03, &84, &06, &06, &06, &06, &06, &42, &48, &09, &a9, &09, &ac, &06, &56, &42, &06, &06, &06, &06, &ac, &03, &a9, &81, &09, &a9, &09, &06, &a9, &5c, &84, &e8, &09, &09, &42, &81, &c0, &c0, &81, &81, &81, &80
	db &04, &03, &03, &09, &06, &03, &03, &09, &09, &84, &81, &c0, &48, &09, &09, &09, &ac, &06, &06, &03, &09, &56, &03, &03, &09, &09, &5c, &06, &06, &56, &09, &48, &43, &81, &56, &d4, &09, &c0, &c0, &c0, &42, &c0, &c0, &e8, &02
	db &01, &06, &03, &06, &03, &09, &5c, &06, &06, &a9, &c0, &42, &42, &a9, &09, &e8, &09, &42, &a9, &d4, &03, &09, &0c, &06, &06, &06, &06, &06, &56, &09, &56, &06, &e8, &ac, &84, &06, &d4, &c0, &81, &c0, &c0, &42, &e8, &42, &80
	db &01, &03, &06, &03, &09, &09, &06, &a9, &09, &0c, &84, &84, &84, &81, &09, &09, &06, &03, &09, &42, &06, &03, &03, &a9, &56, &03, &56, &06, &06, &06, &06, &03, &09, &81, &42, &a9, &48, &42, &c0, &c0, &c0, &c0, &42, &e8, &02
	db &01, &09, &09, &06, &56, &06, &a9, &09, &09, &a9, &48, &42, &06, &42, &03, &5c, &d4, &06, &42, &09, &42, &06, &06, &06, &06, &06, &06, &42, &56, &06, &56, &09, &06, &ac, &81, &48, &42, &c0, &42, &c0, &c0, &c0, &81, &84, &80
	db &01, &03, &81, &a9, &06, &03, &09, &a9, &0c, &06, &e8, &48, &84, &84, &e8, &06, &06, &42, &a9, &03, &09, &06, &03, &09, &06, &06, &03, &ac, &06, &06, &42, &ac, &42, &56, &d4, &84, &06, &c0, &c0, &c0, &81, &c0, &c0, &42, &02
	db &01, &09, &09, &09, &09, &ac, &06, &84, &03, &09, &09, &81, &d4, &09, &84, &03, &e8, &06, &06, &81, &a9, &81, &06, &03, &09, &56, &84, &03, &81, &e8, &06, &42, &ac, &84, &06, &42, &48, &42, &c0, &c0, &c0, &c0, &42, &e8, &80
	db &54, &03, &a9, &56, &06, &03, &a9, &5c, &09, &5c, &84, &84, &81, &84, &e8, &09, &5c, &81, &06, &42, &03, &09, &81, &09, &03, &09, &06, &06, &06, &06, &56, &06, &03, &81, &84, &e8, &e8, &48, &c0, &c0, &84, &c0, &c0, &42, &80
	db &04, &06, &06, &06, &56, &09, &09, &09, &5c, &06, &42, &81, &0c, &06, &81, &48, &03, &09, &d4, &06, &42, &03, &09, &06, &06, &06, &03, &a9, &09, &56, &06, &42, &e8, &5c, &81, &09, &48, &42, &48, &48, &81, &c0, &81, &84, &02
	db &54, &03, &a9, &a9, &06, &56, &09, &48, &06, &a9, &09, &c0, &c0, &09, &09, &09, &48, &a9, &09, &81, &06, &56, &81, &d4, &03, &a9, &09, &09, &ac, &06, &d4, &06, &42, &06, &d4, &48, &ac, &81, &c0, &42, &c0, &c0, &81, &c0, &02
	db &41, &06, &06, &06, &a9, &09, &48, &06, &06, &42, &42, &81, &5c, &81, &48, &e8, &e8, &09, &81, &09, &e8, &06, &06, &06, &06, &06, &06, &56, &06, &03, &09, &d4, &84, &e8, &09, &84, &42, &e8, &48, &48, &c0, &c0, &c0, &42, &80
	db &54, &56, &56, &03, &09, &09, &0c, &0c, &06, &e8, &09, &c0, &06, &d4, &09, &09, &09, &d4, &09, &84, &56, &81, &a9, &09, &a9, &09, &ac, &06, &06, &a9, &a9, &09, &06, &06, &ac, &ac, &84, &d4, &d4, &84, &42, &c0, &c0, &d4, &80
	db &04, &06, &06, &ac, &06, &06, &06, &06, &03, &81, &d4, &84, &d4, &09, &84, &06, &84, &06, &d4, &81, &84, &06, &42, &06, &06, &56, &06, &56, &06, &06, &06, &42, &e8, &ac, &42, &a9, &09, &84, &81, &c0, &81, &c0, &81, &81, &80
	db &54, &56, &06, &42, &e8, &0c, &06, &06, &84, &06, &42, &03, &48, &06, &e8, &ac, &56, &09, &06, &06, &03, &d4, &06, &a9, &a9, &09, &ac, &06, &56, &56, &d4, &84, &06, &06, &06, &e8, &5c, &81, &48, &ac, &81, &81, &d4, &81, &80
	db &04, &06, &06, &06, &06, &06, &ac, &03, &42, &81, &81, &48, &06, &06, &06, &06, &06, &d4, &09, &d4, &84, &06, &81, &84, &06, &06, &56, &56, &48, &09, &09, &ac, &a9, &ac, &a9, &09, &84, &06, &81, &c0, &06, &d4, &c0, &48, &02
	db &04, &56, &09, &81, &06, &06, &42, &48, &a9, &84, &42, &a9, &84, &81, &5c, &06, &a9, &48, &ac, &06, &06, &42, &ac, &42, &e8, &a9, &09, &09, &a9, &ac, &ac, &06, &06, &a9, &5c, &5c, &d4, &d4, &84, &e8, &42, &42, &42, &e8, &02
	db &01, &09, &06, &06, &81, &09, &09, &81, &81, &81, &d4, &81, &e8, &09, &84, &06, &06, &a9, &09, &5c, &d4, &09, &48, &09, &09, &48, &48, &ac, &84, &03, &09, &ac, &a9, &09, &a9, &06, &06, &06, &81, &84, &42, &e8, &42, &81, &08
	db &01, &09, &81, &81, &42, &42, &03, &06, &81, &48, &06, &06, &03, &ac, &56, &d4, &06, &06, &a9, &09, &09, &5c, &56, &56, &84, &56, &06, &56, &5c, &09, &ac, &56, &09, &ac, &ac, &56, &d4, &81, &48, &d4, &42, &42, &09, &c0, &80
	db &01, &03, &81, &81, &81, &03, &09, &81, &81, &42, &42, &42, &e8, &42, &09, &09, &5c, &06, &06, &ac, &56, &06, &06, &d4, &5c, &06, &56, &09, &56, &5c, &09, &ac, &56, &09, &06, &ac, &06, &42, &42, &42, &06, &42, &e8, &42, &02
	db &40, &09, &06, &81, &48, &42, &03, &03, &48, &56, &84, &03, &09, &a9, &06, &06, &06, &56, &09, &ac, &06, &ac, &56, &09, &5c, &5c, &09, &ac, &06, &56, &06, &a9, &09, &ac, &a9, &09, &e8, &48, &06, &56, &d4, &81, &81, &d4, &80
	db &01, &81, &42, &42, &03, &09, &84, &42, &81, &09, &81, &81, &42, &09, &d4, &d4, &56, &09, &06, &56, &09, &56, &09, &5c, &03, &09, &ac, &06, &a9, &0c, &a9, &5c, &06, &56, &06, &42, &09, &d4, &d4, &81, &42, &06, &42, &42, &80
	db &04, &06, &06, &06, &c0, &03, &42, &03, &e8, &84, &56, &84, &03, &a9, &03, &48, &09, &06, &ac, &06, &ac, &06, &a9, &5c, &09, &ac, &06, &a9, &5c, &06, &a9, &5c, &56, &09, &ac, &e8, &e8, &09, &03, &48, &e8, &42, &e8, &09, &80
	db &01, &81, &03, &81, &84, &42, &56, &06, &42, &42, &42, &42, &e8, &06, &03, &03, &e8, &09, &56, &09, &ac, &a9, &5c, &06, &ac, &56, &56, &5c, &06, &a9, &5c, &83, &09, &09, &81, &84, &42, &56, &d4, &03, &81, &e8, &42, &42, &02
	db &01, &84, &81, &09, &42, &06, &81, &81, &03, &48, &a9, &06, &42, &a9, &d4, &06, &03, &e8, &09, &09, &06, &06, &56, &09, &ac, &06, &e9, &06, &56, &83, &09, &ac, &a9, &5c, &48, &e8, &06, &03, &d4, &06, &42, &03, &81, &d4, &80
	db &01, &03, &a9, &42, &48, &42, &06, &42, &a9, &81, &84, &42, &06, &42, &a9, &81, &e8, &03, &e8, &e8, &a9, &ac, &06, &56, &09, &ac, &56, &5c, &86, &a9, &ac, &03, &48, &42, &42, &09, &e8, &e8, &42, &42, &e8, &42, &e8, &42, &02
	db &01, &84, &81, &03, &e8, &09, &81, &42, &56, &42, &42, &a9, &42, &06, &03, &09, &06, &06, &03, &09, &48, &06, &a9, &09, &5c, &06, &06, &56, &06, &ac, &06, &e8, &ac, &84, &d4, &42, &03, &56, &56, &42, &06, &42, &06, &42, &00
	db &00, &42, &06, &42, &03, &81, &48, &09, &09, &09, &81, &09, &d4, &81, &d4, &42, &56, &42, &a9, &42, &a9, &48, &84, &56, &06, &56, &06, &06, &03, &09, &e8, &06, &81, &a9, &42, &a9, &5c, &84, &81, &81, &81, &81, &81, &80, &00
	db &00, &54, &81, &06, &42, &e8, &03, &81, &81, &56, &81, &81, &09, &06, &42, &a9, &81, &42, &06, &a9, &81, &03, &e8, &84, &84, &84, &56, &d4, &09, &84, &84, &42, &42, &09, &09, &e8, &03, &03, &09, &a9, &d4, &81, &d4, &00, &00
	db &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00
